### ISSUE TITLE
check amount is valid for loop out

### ISSUE THREAD

**Issue by nicolasburtey** [lightninglabs/loop#104]
if I requesting an amount above my outbound capacity, loop out will still proceed and fail the payment will "failed: unable to find a path to destination"

loop should check that the amount requested is equal or below my spending balance.

**Comment by joostjager** [comment]
The reason for requesting this is that you want a quicker response for this failure case?

**Comment by nicolasburtey** [comment]
and also because I will have paid the non-refundable deposit for a transaction that is not possible

**Comment by joostjager** [comment]
If the swap payment doesn't arrive at the server, the deposit should be refunded. Are you seeing otherwise?

**Comment by nicolasburtey** [comment]
I opened the ticket more than 6 months ago, so it might have changed since, but I didn't recall having a refund back then

**Comment by instagibbs** [comment]
I think a simple sanity check of "is this even theoretically possible" before committing any funds would be good ergonomics.

**Comment by justinpobrien** [comment]
Loop should check and fail before attempting to make a payment if any of the following are true: 
- No active channels
- Outbound capacity < Loop out amount

We can also provide a bit more info when the user attempts something that will obviously fail. We ought to also consider similar checks for Loop In

**Comment by ellemouton** [comment]
I started working on this yesterday but completely forgot to claim it here. 
@bhandras, I see you have self assigned it. Have you started already or is it ok if I continue? I think mine is ready for review. I will open the PR anyways but am happy to close it again if needed 👍

**Comment by bhandras** [comment]
> I started working on this yesterday but completely forgot to claim it here.
> @bhandras, I see you have self assigned it. Have you started already or is it ok if I continue? I think mine is ready for review. I will open the PR anyways but am happy to close it again if needed +1

Awesome, re-assigned to you.
