### ISSUE TITLE
SSL Error with REST using Python

### ISSUE THREAD

**Issue by sako0938** [lightninglabs/loop#105]
I have made some code to start trying out loop with the rest API.

```
import base64, json, requests
import codecs
from pprint import pprint

base_url = 'https://127.0.0.1:8081'
url1 = '/v1/loop/in'
url2 = '/v1/loop/in/quote/{}'
url3 = '/v1/loop/out/quote/{}'

LND_DIR = '{mypath}/.lnd/'
cert_path = LND_DIR + 'tls.cert'

def sendGetRequest(endpoint, data=""):
	global base_url
	target_url = base_url + endpoint.format(data)
	print("Sending Request to URL: {}".format(target_url))
	r = requests.get(target_url, verify=cert_path)
	pprint(r.text)
	return r.text

loopreq = sendGetRequest(url2,250000)
```

Receives this error:

>   File "/home/lightning/env/lib/python3.7/site-packages/urllib3/connection.py", line 394, in connect
    ssl_context=context,
  File "/home/lightning/env/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 383, in ssl_wrap_socket
    return context.wrap_socket(sock)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1056)

I can't seem to get past this, and most of the similar cases on the internet involve using the wrong port.

The port specified in the docs also specify port 8080, which succeeds to not find.

> Sending Request to URL: https://127.0.0.1:8080/v1/loop/in/quote/250000
'Not Found\n'

But this makes sense because that is LNDs port.

Using requests 2.22.0
Using loopd master

**Comment by guggero** [comment]
At the moment `loopd` only creates non-TLS connections. So both port `11010` and `8081` are not encrypted.
Your `base_url` should only be `http://127.0.0.1:8081`.

**Comment by sako0938** [comment]
Oh! So remove verify, and use http, not https in the base_url. Thanks.

```
base_url = 'http://127.0.0.1:8081'
def sendGetRequest(endpoint, data=""):
	global base_url
	target_url = base_url + endpoint.format(data)
	print("Sending Request to URL: {}".format(target_url))
	r = requests.get(target_url)
	pprint(r.text)
	return r.text
```
Works for me.

**Comment by guggero** [comment]
Ah, yes, didn't see the `verify=cert_path` before. Good to hear that it works!
