### ISSUE TITLE
Document loop out delay feature, and better logging/monitor

### ISSUE THREAD

**Issue by sako0938** [lightninglabs/loop#114]
Using the master branch loop 0.3.0, and the REST API I was trying to test if I could get some loop outs to be batched.

1. The ```swap_publication_deadline``` was set to 7200, which I thought would be enough time to get a few transactions through. I did maybe 3-4 loop out txns, and 1 failed (bad channel), 1 succeeded (good channel), then 2 succeeded (good both same channel). After checking the block explorer, it did not batch at all.

Maybe a minimum swap_publication_min could also be added, but I don't know exactly why loopd decided to complete the swap so quickly and not batch.

2. Logging loop in/out parameters to log/ loop monitor. After sending the request, it is difficult to tell fee rate settings, as they aren't logged. As I am setting fee limits, it is difficult to tell if the server uses max fees that I specify each time, or that I got a deal because of ```swap_publication_deadline``` or ```conf_target```.

The channel_id is actually shown in the logs, but it is in hex form, and not the other form distributed around LND, so it is less useful (converting to base10 doesnt help, would need to dive in to make a conversion.)

**Comment by guggero** [comment]
I agree there should be better documentation on this and we are working on it.

The description of the `swap_publication_deadline` is as follows:

> The latest time (in unix seconds) we allow the server to wait before publishing the HTLC on chain.

Which means, it needs to be a UNIX timestamp that is in the future, not an absolute number of seconds. The wording here is maybe not optimal.
Your 7200 seconds were interpreted as 1970-01-01T02:00 which is in the past and therefore an immediate swap was issued.

**Comment by sako0938** [comment]
Awesome, that makes a lot of sense.
Trying it again now with it properly.
```
'swap_publication_deadline': floor((datetime.now() + timedelta(hours=2)).timestamp())`
```

**Comment by guggero** [comment]
The new parameters are now also documented in our loop API doc: https://lightning.engineering/loopapi/#unary-rpc, closing the issue as there's no action pending anymore IMO.
