### ISSUE TITLE
Loops stuck in initiated

### ISSUE THREAD

**Issue by tdickman** [lightninglabs/loop#118]
I have 4 loop out attempts from yesterday that have been stuck in the `INITIATED` state for > 24 hours without transitioning. What's the best way for me to check on the status of these / make sure I have no funds locked up?

These loop out attempts were made with a `conf_target` of 50.

**Comment by tdickman** [comment]
It's hard for me to tell if this is related, but one of the channels involved with one of the loop out operations just failed in the same block the channel was force closed. Don't know which one caused which thought.

**Comment by tdickman** [comment]
Another channel that was involved just force closed, so this is definitely related.

**Comment by joostjager** [comment]
Did you learn anything new about this question in the meantime @tdickman? 

`loopd` logs may tell more about what was going on.

**Comment by joostjager** [comment]
Closing for now. Feel free to reopen if new info emerges
