### ISSUE TITLE
Loop out successful but off-chain funds not released

### ISSUE THREAD

**Issue by bb2k16** [lightninglabs/loop#124]
![image](https://user-images.githubusercontent.com/22429074/70668464-9d0a5580-1c6b-11ea-896f-3f29d6a4c56a.png)

LOOPD keeps loggined "the payment already in flight"

LND keeps logging "unable to send payment: payment is in transition"

Loop mintor says the preimage is revaled.

And I have already recieved the loop out BTC on chain. (loop out address: bc1qvufunsdpm9zsuu483eld0gl6sz052mg7lucte7)

Tx ID: d2c0c35f7279e54ca643e1eee42889ac5729916ca18d2c5d2dafd672f7380ae0

2,000,000 sat stuck on the channel waiting to be released.

loop version: 0.3.0 alpha
OS: Windows 10

Could this be looked into, or would it resolve itself?

**Comment by halseth** [comment]
Duplicate? https://github.com/lightninglabs/loop/issues/117

**Comment by halseth** [comment]
@joostjager Do you know why it would retry sending if swap already completed?

**Comment by joostjager** [comment]
We still use the main rpc for sending the payment: https://github.com/lightninglabs/loop/blob/736daafb5af38891689170fd120594b6dd77625c/lndclient/lightning_client.go#L259

That doesn't allow reliable tracking, so we 'poll' the payment to get its status.

It seems that the htlc is/was stuck.

**Comment by joostjager** [comment]
This should now be resolved by switching to `routerrpc` in https://github.com/lightninglabs/loop/pull/178
