### ISSUE TITLE
Need transactional record for loop operations

### ISSUE THREAD

**Issue by saubyk** [lightninglabs/loop#126]
Each loop operation consists of two legs, a lightning transaction and an on-chain transaction.
Currently there is no clear way to identify each loop operation, as a transaction comprised of these two legs. This results in difficulty while tracking the transaction both during the loop operation as well as after the loop has completed successfully.

Ideally each loop operation attempted via the loop server should be provided as a list via the apis. The apis should also list the transaction legs of the loop operation:
Loop Out: 
- The Invoice which has been paid
- On-chain sweep transaction

Loop In:
- On-chain transaction paid
- Invoice which is expected to be settled

This should help design the UI solutions better as it provides better traceability of the action both during and after the operation has been completed. The current tracking solution of `loop monitor` is not ideal for integration with the user interfaces.

**Comment by kaloudis** [comment]
Yes, please

**Comment by tdickman** [comment]
I'm creating a tool that automates loop out operations for a node, and need a way to keep track of what channel both successful and unsuccessful loop operations are associated with, so I'd love for this to be added as well.

**Comment by Roasbeef** [comment]
I think the ['`SwapInfo`](https://lightning.engineering/loopapi/index.html#swapinfo) call addresses this?

**Comment by saubyk** [comment]
Hi @Roasbeef Yes SwapInfo addresses the requirement on this ticket to a large extent. 

Although my original expectation was to club all the on-chain and off-chain transactions involved in one loop request together, so that user can easily track all the activity together.

We can re-visit that in the future, depending on how the service evolves. Closing this ticket. Thanks.
