### ISSUE TITLE
rpc: add TLS for loopd clients

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/loop#13]
As is today, one can only hit the loopd API over local host on the same machine. As we want to be able to support more advanced configuration with remote lnd and loopd nodes, we should expand the client RPC server to support TLS. Much of this can be borrowed from lnd

**Comment by joostjager** [comment]
Copied desc from #194

**Comment by joostjager** [comment]
Closing because just adding a server certificate doesn't offer any form of authentication of the client.
