### ISSUE TITLE
Overpaid `loop in --external` htlc. Timeout transaction unable to broadcast.

### ISSUE THREAD

**Issue by githorray** [lightninglabs/loop#134]
Accidentally overpaid an external loop in htlc.

I was a bit confused by how much to pay as the instructions displayed at the time of the htlc creation with the loop cli mentioned both the loop in amount and a fee. 

I misunderstood that the total amount sent to the htlc address should JUST be the loop in amount requested and that the loop in fee would be deducted from the lightning payment. I paid BOTH the loop in amount and the loop in fee to the external htlc address.

Just a slight total over-payment of about 1000 sats.

Waited 1000 blocks for htlc timeout. loopd created the timeout tx `LOOP: Publishing timeout tx`, and sent it to lnd for broadcast `[INF] LNWL: Inserting unconfirmed transaction`. 

tx never appeared in mempool. loopd kept submitting timeout transactions building up a larger and larger `unconfirmed_balance` in lnd.

Tried broadcasting the timeout transaction created by loopd manually by obtaining the raw tx from `lncli listchaintxns`. Received the following error:

`sendrawtransaction RPC error: {"code":-26,"message":"non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation) (code 64)"}`

LND on mainnet with neutrino:
`$ lnd --version
lnd version 0.9.0-beta commit=v0.9.0-beta-rc1-30-g269182c9b9f140612ba020b56bd1627c53cf88f0`

Loop:
`$ loopd -V
loopd version 0.3.1-alpha commit=`

**Comment by joostjager** [comment]
We've identified the issue in the `loop` client code and are working on a fix.

**Comment by joostjager** [comment]
Running the updated `loop` client should republish the timeout transaction with the correct signature.
