### ISSUE TITLE
API for fee details which are available in the CLI response 

### ISSUE THREAD

**Issue by saubyk** [lightninglabs/loop#142]
The existing quote apis should be enhanced or a new api created to provide the fee details output which is available on the loop out/in cli response.
E.g. an api providing an output similar to the cli response response below for loop-out:
```
$ loop out 2000000
Max swap fees for 2000000 Loop Out: 41543
Regular swap speed requested, it might take up to 30m0s for the swap to be executed.
CONTINUE SWAP? (y/n), expand fee detail (x): x

Max on-chain fee:                 447
Max off-chain swap routing fee:   40010
Max off-chain prepay routing fee: 36
Max swap fee:                     1050
Max no show penalty:              1337
```
Similarly an api for the cli response for loop-in:
```
$ loop in 250000
Max swap fees for 250000 Loop In: 812
CONTINUE SWAP? (y/n), expand fee detail (x): x

Max on-chain fee:                 462
Max swap fee:                     350
```

**Comment by halseth** [comment]
The details shown on the CLI are extracted from the `QuoteResponse` as shown here: https://github.com/lightninglabs/loop/blob/master/cmd/loop/main.go#L124

Would doing something similar cover your use case?

**Comment by ShahanaFarooqui** [comment]
@halseth, If we can get the values for `Max Off-chain Prepay Routing Fee` & `Max On-chain Fee`, it will cover our use case. But, looks like both are missing at above link.

**Comment by halseth** [comment]
@ShahanaFarooqui `Max on-chain fee` is called `maxMinerFee` in the link above. `maxPrepayRoutingFee` is the `Max Off-chain Prepay Routing Fee`.

**Comment by ShahanaFarooqui** [comment]
Then that should work for loop/out. 

For loop/in, we will need 'max_swap_fee' and 'max_miner_fee' values only, which we are able to get from loop/in/quote API.

**Comment by alexbosworth** [comment]
You should be able to ignore the max miner fee, do you need the max swap fee?

the max swap fee can also be ignored if you confirm the fee itself

**Comment by halseth** [comment]
@ShahanaFarooqui From https://github.com/lightninglabs/loop/issues/142#issuecomment-596574045 am I correct that this issue can be closed?

**Comment by ShahanaFarooqui** [comment]
@halseth, Discussed with @saubyk and we have the required information. This ticket can be closed.
