### ISSUE TITLE
Missing CORS headers for loop monitor REST

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#146]
Loop version 0.4.0-beta

Loop monitor REST GET api at 'http://localhost:8081/v1/loop/monitor' is throwing CORS errors:
![image](https://user-images.githubusercontent.com/23240721/73864677-0fcd2280-4810-11ea-818d-898020aa60a9.png)

**Comment by ShahanaFarooqui** [comment]
@guggero I am receiving the same error with v0.4.1 as well. But, all other APIs, except monitor, are working on REST without any error.

v0.4.1:
![image](https://user-images.githubusercontent.com/23240721/74355923-7fe92480-4d8b-11ea-9f53-3fd0b9ea1365.png)

Error:
![image](https://user-images.githubusercontent.com/23240721/74355963-91cac780-4d8b-11ea-8d55-c95d05097562.png)

**Comment by guggero** [comment]
Hmm... I probably shouldn't have exposed an URL for the monitor call, the streaming mechanism works differently from the other calls and is not really user friendly with REST. Is there anything missing in the synchronous calls (`/v1/loop/swaps` or `/v1/loop/swap/<hash>`)? Or did you just want to use the monitor stream for performance reasons?

**Comment by ShahanaFarooqui** [comment]
We want to show streamed/live updates from monitor on the UI.

**Comment by ShahanaFarooqui** [comment]
@guggero where can i find the documentation for swap?

**Comment by saubyk** [comment]
@guggero agree with you.
The swaps and swap apis are good for us to meet the requirements of the user interface.

Monitor api is not a good solution for the UI anyway as I have already raised in the below issue:
https://github.com/lightninglabs/loop/issues/126

**Comment by ShahanaFarooqui** [comment]
@guggero looks like swap/<hash> api is not decoding the route parameter (id), which can contain "/". We opened another issue #154 with details.
