### ISSUE TITLE
CORS error for loop monitor REST in v0.4.1

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#153]
Loop version 0.4.1-beta

Loop monitor REST GET api at 'http://localhost:8081/v1/loop/monitor' is throwing CORS error. But, all other APIs, except monitor, are working as expected on REST without any issue.

Loop Logs with other working REST requests:
![image](https://user-images.githubusercontent.com/23240721/74357638-31895500-4d8e-11ea-95d5-f866eefdb0d5.png)

Console error for REST monitor:
![image](https://user-images.githubusercontent.com/23240721/74357702-44038e80-4d8e-11ea-88ef-08284a27cc3b.png)

**Comment by alexbosworth** [comment]
Is there anything wrong with just using the polling method?

**Comment by ShahanaFarooqui** [comment]
Polling will exponentially increase the time complexity for the UI. But, we are able to move forward without monitor as suggested by Oli #146. We are using swaps & swap API to get the final status. I was not sure if i should leave this issue open for other users or not.

**Comment by alexbosworth** [comment]
OK let's leave it open while we still have this API available

**Comment by guggero** [comment]
I added #156 to remove the endpoint.

**Comment by guggero** [comment]
Fixed with #156.
