### ISSUE TITLE
Loop in quote fee is same for different swap_publication_deadline(--fast)

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#162]
Loop v 0.5.0

Loop in quote api accepts swap_publication_deadline as a query param for fast/slow flag. But the swap fee in the response is the same for all values.

Request 1:
http://localhost:8081/v1/loop/in/quote/250000?conf_target=6&swap_publication_deadline=0

Return response 1:
{
    "swap_fee": "350",
    "prepay_amt": "0",
    "miner_fee": "224",
    "swap_payment_dest": null,
    "cltv_delta": 0
}

Request 2:
http://localhost:8081/v1/loop/in/quote/250000?conf_target=6&swap_publication_deadline=<30minsdelay>

Return response 2:
{
    "swap_fee": "350",
    "prepay_amt": "0",
    "miner_fee": "224",
    "swap_payment_dest": null,
    "cltv_delta": 0
}

**Comment by alexbosworth** [comment]
Currently there wouldn't be a difference, so an equal result would be accurate
