### ISSUE TITLE
Missing swap_publication_deadline for Loop In

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#163]
Loop v0.5.0

'loop/in/quote' API has the provision to get `swap_publication_deadline` through queryparam but LoopIn (POST 'loop/in') is not accepting swap_publication_deadline value. 

So, either loopInQuote should also not have 'swap_publication_deadline' options OR loopIn should also accept it in the request.

**Comment by Roasbeef** [comment]
Loop in doesn't have any sort of delay atm, since that would require aggregation at the client level.

**Comment by joostjager** [comment]
The doc on field `QuoteRequest.swap_publication_deadline` says:

>This only has an effect on loop out quotes.

Feel free to reopen if misunderstood.
