### ISSUE TITLE
Implement loop in on-chain fee reporting

### ISSUE THREAD

**Issue by joostjager** [lightninglabs/loop#189]
Currently the miner fee that was spent for the on-chain htlc isn't tracked. This is also visible in the client log when a swap is completed:

`Loop in swap completed: Success (final cost: server 0.00002505 BTC, onchain 0 BTC, offchain 0 BTC)`

`onchain` should never be zero.

**Comment by carlaKC** [comment]
Picking this up, required for autoloop-in to have proper awareness of its use of funds.
