### ISSUE TITLE
rpc: add tls and macaroon auth for loopd clients

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/loop#194]
As is today, one can only hit the loopd API over local host on the same machine. As we want to be able to support more advanced configuration with remote lnd and loopd nodes, we should expand the client RPC server to support TLS and also macaroons. Much of this can be borrowed from lnd. To start a simple read and write macaroon should suffice. In the future we can also leverage the bakery to bake more granular macaroons.

**Comment by joostjager** [comment]
Partial duplicate (TLS part) of #13. Can you move the TLS part into #13, so we have two distinct issues? They are related of course, but TLS can be implement first

**Comment by joostjager** [comment]
Moved TLS description to #13

**Comment by sako0938** [comment]
I am interested in this issue. I have scripts for interacting with the LND rest API, and that connects to a remote LND instance. It is a lot less useful to have to SSH into my node server in order to run my REST loop script. I end up just using the CLI most of the time, instead of the API because of this.

**Comment by joostjager** [comment]
Are you interested in macaroons (this issue) or TLS (#13)? I guess it must be TLS?

**Comment by sako0938** [comment]
I would think macaroons, whatever would allow the loop REST api to run on 0.0.0.0:8081, instead of localhost:8081

**Comment by joostjager** [comment]
Restored issue description to original description after realizing that a server certificate on its own doesn't prevent anyone from accessing the server. So as originally stated, we need both macaroons and tls.
