### ISSUE TITLE
loop out: allow outbound channel set for multi-loops

### ISSUE THREAD

**Issue by joostjager** [lightninglabs/loop#195]
Currently loop out supports multi-loops (looping out multiple channels in one operation using MPP). But there is no control over which channels are used for the payment.

This issue adds the ability for the user to indicate a set of channels which are all allowed to be used in the swap.

Depends https://github.com/lightningnetwork/lnd/pull/4257

**Comment by joostjager** [comment]
@alexbosworth should we spend extra time to allow upgrading the loop client with pending swaps? That would mean we need to support both script versions client-side and also persist the script version in the database (for resumes).

**Comment by alexbosworth** [comment]
> @alexbosworth should we spend extra time to allow upgrading the loop client with pending swaps? That would mean we need to support both script versions client-side and also persist the script version in the database (for resumes).

Is this the right issue? I am lacking context here

**Comment by joostjager** [comment]
Issue replaced by PR https://github.com/lightninglabs/loop/pull/205
