### ISSUE TITLE
Add sat_per_byte parameter

### ISSUE THREAD

**Issue by bb2k16** [lightninglabs/loop#207]
I understand that this was previously requested, and confirmation time parameter was added for loopout. To some extend it worked, but with the limit only around 80 blocks, this is only sufficient to certain extend, but doesnt crater for clients that would rather pay at the exact satoshi per byte who doesn't mind the wait.

is this possible to add or is this a bad idea?

**Comment by joostjager** [comment]
I've added info about whether it is a bad idea to https://github.com/lightninglabs/loop/issues/229. Closing this issue, so we can centralize the discussion there.
