### ISSUE TITLE
Prevent start of downgraded cient if protocol version is incompatible

### ISSUE THREAD

**Issue by bhandras** [lightninglabs/loop#218]
Whenever a user would like to downgrade their loop client we should prevent `loopd` startup if the current protocol version is incompatible with the client protocol version.

An example of this issue is when a client wants to downgrade their client while they have a native segwit loop-in swap in progress. The swap may fail as the client may expect confirmation for the wrong htlc, and the funds may need to be manually swept.

**Comment by joostjager** [comment]
My initial thought is to bump the database version if we move to a newer protocol version from which a downgrade is impossible.

**Comment by joostjager** [comment]
We just merged #238, so all changes up to that pr have been locked in now.

**Comment by bhandras** [comment]
Closing this, bumping the db version is sufficient to prevent clients from downgrading.

**Comment by carlaKC** [comment]
Did we need to bump version for native segwit? Can't remember whether the outcome of the discussion there was that it was unnecessary.

**Comment by joostjager** [comment]
Yes we needed to bump. After a downgraded, the p2wsh loop in wouldn't be recognized
