### ISSUE TITLE
Max_sat_per_byte adjustable and no hurry swaps for 300sats

### ISSUE THREAD

**Issue by HTransistor** [lightninglabs/loop#229]
### Background
Tried to do a loop out, way too expensive to be useful.
This is what i got in console:
loop out -max_swap_routing_fee=300 250000
Max swap fees for 250000 sat Loop Out: 15861 sat
Regular swap speed requested, it might take up to 30m0s for the swap to be executed.
CONTINUE SWAP? (y/n), expand fee detail (x): x

Estimated on-chain sweep fee:        149 sat
Max on-chain sweep fee:              14900 sat
Max off-chain swap routing fee:      300 sat
Max no show penalty (prepay):        1337 sat
Max off-chain prepay routing fee:    36 sat
Max swap fee:                        625 sat

Describe your issue here.
Is it possible to set the max on-chain sweep fee?
Even though it is a max fee, but I would not like it to reach it in any case. Can I set my own max, that it cancels, when it would exceed it? I mean basically I want to my max pay fee to be in the region of 300sat (I would like to be able to set the maximum of all the listed payfees (especially the most expensive ones).
I mean setting up channels is nothing what I am doing in a hurry. My on-chain tx gets sometimes 1sat/byte so 200sat/tx in 30min (sometimes 2days). I would like to have similiar tx fee for channel funding/loop in / loop out, because then I would have  an increase in speed (for free) and therefore have a reason to use the lightning network. I would have an advantage even in the case when i suddenly want to withdraw my funds.

### Your environment

* version of `lnd` lncli version 0.10.1-beta commit=v0.10.1-beta
* which operating system (`uname -a` on *Nix) Linux dsche-pc 5.6.16-1-MANJARO #1 SMP PREEMPT Wed Jun 3 14:26:28 UTC 2020 x86_64 GNU/Linux

* version of `btcd`, `bitcoind`, or other backend Bitcoin Core version v0.20.0
* any other relevant environment details

### Steps to reproduce

Tell us how to reproduce this issue. Please provide stacktraces and links to code in question.

### Expected behaviour
I would like to be able to set the maximum of all the listed payfees (epecially the most expensive ones).

Tell us what should happen

### Actual behaviour
Can't use loop as it is too expensive (in worst-case).
Tell us what happens instead

**Comment by joostjager** [comment]
One thing to be aware of is that if you don't get your sweep confirmed before the htlc expires, you get into a potential race condition with the server. After expiry, both your sweep and the server timeout transaction are valid. If the server is malicious, you could lose the full swap amount.

This is also the reason why the max on-chain fee is set high. In case the fee market goes up, it may be needed to pay a lot more than the original estimate to get into the chain in time.

The primary control for the on-chain fee paid is the `--conf_target` parameter. If you set that to a high value, the on-chain fee paid should be lower.

There is a safety mechanism though. Currently at height `expiry - 12`, `loopd` switches to using a 6 conf target regardless of what was specified for the `conf_target` parameter. Again to increase chances to get our sweep confirmed in time.

If that proposed max on-chain fee parameter is added, you have to be aware that this may effectively disable the safety mechanism and you'd need to trust the server.

Have you already tried to work with longer conf targets and see what the actually paid fee works out to?

**Comment by HTransistor** [comment]
loop out  -amt=250000 -conf_target=70 -max_swap_routing_fee=300 -addr=MY_SECRET_ADDRESS
Max swap fees for 250000 sat Loop Out: 15861 sat
Regular swap speed requested, it might take up to 30m0s for the swap to be executed.
CONTINUE SWAP? (y/n), expand fee detail (x): x

Estimated on-chain sweep fee:        149 sat
Max on-chain sweep fee:              14900 sat
Max off-chain swap routing fee:      300 sat
Max no show penalty (prepay):        1337 sat
Max off-chain prepay routing fee:    36 sat
Max swap fee:                        625 sat

Can you adjust the htlc timeout to higher values? How do I now what height expiry is? If htlc times out I want my sats back to my on-chain address. I don't want to hope to get low sweep fees and if it goes trough for a high sweep fee, to regret that I didn't stay on-chain.

**Comment by joostjager** [comment]
With 'try to work with longer conf target' I meant initiating the swap and observing the actual fee paid. But as mentioned by @bb2k16 as well in https://github.com/lightninglabs/loop/issues/207#issue-621267634, it may still be too high. And you may also want to prevent any surprises.

Currently the htlc expiry cannot be changed, but we are considering implementation of that. One concern that we've had is that slow sweeps keep the htlc pending on the network for a long time, but for the latest `loop` release that has been addressed via https://github.com/lightninglabs/loop/pull/193.

What htlc expiry delta would you pick if this were possible? Need to take into account that the payment must remain routable on Lightning. Note that even with a higher delta value, there is still the possibility of the htlc not confirming in time. In that case, would you want the emergency mechanism described above to activate?

**Comment by HTransistor** [comment]
Yeah, I would lime to have something like 2days to 5days (basically adjustable to the level it would take to get a on-chain tx done). Of course then you would also need something to check the pending tx (in terms of how long will it need/ is there even a possiblity to get it through).
And yes, when it doesn't go through (emergency):
My runds back to a given address. Also prompting me to try again with higher time out or higher fees.

**Comment by HTransistor** [comment]
loop out -amt=250000 -conf_target=70 -max_swap_routing_fee=300 -addr=MY_EMERGENCY_ON_CHAIN_ADDRESS
Max swap fees for 250000 sat Loop Out: 223261 sat
Regular swap speed requested, it might take up to 30m0s for the swap to be executed.
CONTINUE SWAP? (y/n), expand fee detail (x): x

Estimated on-chain sweep fee:        2223 sat
Max on-chain sweep fee:              222300 sat
Max off-chain swap routing fee:      300 sat
Max no show penalty (prepay):        1337 sat
Max off-chain prepay routing fee:    36 sat
Max swap fee:                        625 sat

I was just thinking maybe I give it a try 15k sats, but now the max is like 80%, seems like there is no upper limit at all.

**Comment by joostjager** [comment]
You can't just get your funds back to a given address. The problem is that your sweep isn't confirming while you already revealed the preimage. So the only thing that you've really got at that point is that htlc on-chain.
