### ISSUE TITLE
No info on the current loop out send limit in the docs?

### ISSUE THREAD

**Issue by johnblanc** [lightninglabs/loop#244]
Since your slack link in the documentation has expired, I'll have to ask here.
What is the current limit of funds that can be looped out? In the Alpha it was 0.01 BTC but for the beta I can't find it in the documentation if it has been updated?

**Comment by joostjager** [comment]
It isn't documented, but you can retrieve it through the `loop terms` command.

**Comment by johnblanc** [comment]
Thank you! I don't have installed loop yet, since I'm on c-lightning but looking into it!
What is the initial inbound capacity you can get with loop currently? 
And has anyone tested looping it again and again to increase it in practice? I saw that mentioned in one of the blog posts.
Sorry for turning this into chat, but slack invite link is expired and there doesn't seem to be other community where people can discuss those things?

**Comment by joostjager** [comment]
Did you use https://lightning.engineering/slack.html ?

**Comment by Roasbeef** [comment]
Closing as the limit is dynamic, so best obtained via the `loop terms` command.
