### ISSUE TITLE
Surface state updates from the server 

### ISSUE THREAD

**Issue by carlaKC** [lightninglabs/loop#251]
#226 updates loopd to consume a stream of updates from the server and log them. This change does so on a best-effort basis, and does not recover from server restarts. Any further use of this stream should add restart-recovery for the client. 

The updates we get from the server are separate to the updates that loop currently exposes over the loop monitor endpoint, because the server and client represent two sides of the same swap. We need to decide how we want to display these updates - unified with the client updates we currently serve, or as a separate field. 

The subscription endpoint can also be used to provide a once off lookup of the final state that a swap ended on (according to the server), which allows historical lookup for swaps that completed before we implemented this endpoint.

**Comment by carlaKC** [comment]
current set of updates from the server:
```
enum ServerSwapState {
    // The server has created the swap.
    INITIATED = 0;

    // The server has published the loop out on chain htlc.
    HTLC_PUBLISHED = 1;

    // The swap completed successfully.
    SUCCESS = 2;

    /*
    The swap failed for a reason that is unknown to the server, this is only
    set for older swaps.
    */
    FAILED_UNKNOWN = 3;

    // No htlc was confirmed in time for the loop in swap to complete.
    FAILED_NO_HTLC = 4;

    // A loop in htlc confirmed on chain, but it did not have the correct value.
    FAILED_INVALID_HTLC_AMOUNT = 5;

    /*
    We did not succeed in completing the loop in off chain payment before the
    timeout.
    */
    FAILED_OFF_CHAIN_TIMEOUT = 6;

    // The on chain timeout was claimed.
    FAILED_TIMEOUT = 7;

    /*
    The server could not publish the loop out on chain htlc before the deadline
    provided.
    */
    FAILED_SWAP_DEADLINE = 8;

    // The server could not publish the loop out on chain htlc.
    FAILED_HTLC_PUBLICATION = 9;

    // The server has published the loop out on chain timeout tx.
    TIMEOUT_PUBLISHED = 10;

    // The swap has failed for unknown reasons, it will not be completed.
    UNEXPECTED_FAILURE = 11;

    // The swap htlc has confirmed on chain.
    HTLC_CONFIRMED = 12;
}
```

**Comment by jamaljsr** [comment]
I pulled this branch and tested it locally. Looks great! Having this data available on the client will be a huge improvement over the single failure state we have now.

I would prefer this state be a separate field than the current client state field. I think blending the two has the potential of breaking backwards compatibility for existing consumers of the RPC since there will be more state values that their app may not handle properly.

It would be great if this value was made available in the `monitor` endpoint so that the UI could automatically update when the state changes on the server. I'd also like the value to be persisted with the `listswaps` data. Since we use this data to display the loop history in the UI. This is probably more important than having it in `monitor`.

**Comment by joostjager** [comment]
>Having this data available on the client will be a huge improvement over the single failure state we have now.

Are you sure you mean the actual server state updates? Because we also still have client state updates that aren't surfaced on the rpc.

**Comment by jamaljsr** [comment]
> Are you sure you mean the actual server state updates? Because we also still have client state updates that aren't surfaced on the rpc.

The "single failure state" I am referring to is the one exposed by `monitor` and `listswaps` via [SwapStatus](https://github.com/lightninglabs/loop/blob/master/looprpc/client.proto#L312). If there are additional states on the client, then I am not aware of them.

**Comment by carlaKC** [comment]
What we have on the client side is: 

```
StateFailOffchainPayments
StateFailTimeout SwapState = 4
StateFailSweepTimeout
StateFailSweepTimeout SwapState = 5
StateFailInsufficientValue SwapState = 6
StateFailIncorrectHtlcAmt SwapState = 10
StateFailTemporary SwapState = 7
```

Which is all currently squashed down to `Failure`. Will open another issue for this, since it's a quick fix. Only question there is whether we want to keep it in the same state enum, or add a separate failure reason one. 


> I would prefer this state be a separate field than the current client state field.

This sounds good to me, I'm also worried about trying to force the two together. 


> It would be great if this value was made available in the `monitor` endpoint so that the UI could automatically update when the state changes on the server. I'd also like the value to be persisted with the `listswaps` data. Since we use this data to display the loop history in the UI. This is probably more important than having it in `monitor`.

This is really helpful. I think first step is to un-squash client side failure reasons, then look at persisting server udpates (see whether we still need to).

**Comment by joostjager** [comment]
Just opened that issue (https://github.com/lightninglabs/loop/issues/252) and then read your comment @carlaKC. So it is there now.
