### ISSUE TITLE
loop out tocken issue? RTL, mainnet

### ISSUE THREAD

**Issue by bimmerr2019** [lightninglabs/loop#262]
when i try to loop out i get the message: Error: {"error":"cannot initiate swap: payment tracking failed with state FAILED. consider removing pending token file if error persists. use 'listauth' command to find out token file name","code":2,"message":"cannot initiate swap: payment tracking failed with state FAILED. consider removing pending token file if error persists. use 'listauth' command to find out token file name","details":[]}

**Comment by bimmerr2019** [comment]
i solved this myself by deleting the LSAT token:

sudo rm /home/bitcoin/.loop/mainnet/lsat.token.pending

**Comment by alexbosworth** [comment]
This is a known issue that can occur, yes deleting the pending LSAT token is the fix

Ideally Loop should handle this scenario itself
