### ISSUE TITLE
Support for regtest

### ISSUE THREAD

**Issue by mrfelton** [lightninglabs/loop#276]
Need to be able to able to run loop on a regtest network (in my case as part of larger cluster of bitcoind/lnd regtest nodes running via docker-compose). This would enable ability to integrate the daemon into existing development and testing stack, build and run integration tests effectively, and leverage loop in a local development and testing environment without the delays associated with testnet.

Currently, attempting the start with `--network=regtest` results in following error:

> no swap server address specified

**Comment by rockstardev** [comment]
Well, theoretically you could try with bringing up testnet node remotely and we use that in our development stack over some facade (like we do for CMT).

To me it definitely seems like we should refocus this effort into defining api of dedicated service which would wrap receive+utxo management+send and abstract implementation details (is it local loop, remote loop, direct send/receive from LND node).

**Comment by bryanvu** [comment]
@mrfelton one of the complexities in providing comprehensive regtest support for Loop as a services is that there are server-side code and configuration changes that are made on a regular basis that Loop users generally don't have to be concerned with. If we were to build out regtest solution, keeping those regtest users synced up could be a significant drain on the Loop development team as well as a burden for regtest users.

Could you potentially give us some detail on some of the areas you'd want to cover in terms of your test suite? Ideally, we would find ways to address the key concerns in a way that wouldn't require ongoing developer time to support. Also, are there different things you'd want to test during initial integration vs. ongoing usage?

**Comment by Kixunil** [comment]
I need this feature too. I maintain [Cryptoanarchy Debian Repository](https://deb.ln-ask.me) and want to integrate loop as soon as the new version with authentication is released. One of the tasks I will have to do is testing it.

Testing it on mainnet or even testnet would be really terrible. The tests already take significant amount of time and adding tens of minutes (if we include channel opening etc) to them sounds pretty bad. Further, my testing infrastructure is not prepared for getting coins from an external source. As a result I'd be probably forced to test it manually, which would decrease my reaction time to new releases of loop.

What I need is basically an instance of swap server which I can point to an LND using a configuration file (address, macaroon file, cert). I don't think I need anything fancier. If regtest gets supported I will also add it to [lnpbp-testkit](https://github.com/Kixunil/lnpbp-testkit) which could make development of software using `loop` easier for other developers as well.
