### ISSUE TITLE
CMD: loop parameter name

### ISSUE THREAD

**Issue by grunch** [lightninglabs/loop#28]
### Background
On global options of `loop` command, I think the `loopd` parameter name is redundant and we can be more specific like in `lncli` command, this should be changed to `rpcserver`.

### Expected behaviour
```
GLOBAL OPTIONS:
   --rpcserver value  loopd daemon address host:port (default: "localhost:11010")
```
### Actual behaviour
```
GLOBAL OPTIONS:
   --loopd value  loopd daemon address host:port (default: "localhost:11010")
```
### Your environment
* loop commit 769c69e512d2ea57e814e8df354a1a340f11c133
* Linux microbet 4.14.73-136 #1 SMP PREEMPT Mon Oct 1 03:21:48 UTC 2018 armv7l armv7l armv7l GNU/Linux

**Comment by Roasbeef** [comment]
Fixed by #29.
