### ISSUE TITLE
[Support] is AMP supported (funding multiple channels in one go)?

### ISSUE THREAD

**Issue by Talkless** [lightninglabs/loop#288]
Hi,

I see no mention of AMP in issues, README, code.

Will remote  `loop` part try multipart payments to refill my ~6 active channels with funds on the outer side, using *single* on-chain transaction, single `loop in`?

Thanks!

**Comment by carlaKC** [comment]
We support multi-part-payments for loop out, so you can acquire inbound on multiple channels with a single loop out. At present we do not support MPP loop in, so you would not be able to refill multiple channels at once. 

> I see no mention of AMP

Also just a note that AMP is still under discussion on in the spec, whereas MPP is what's recently been added. So right now when you do a multi-path payment, it's MPP, there are some technical differences in how the two work. 

If multi-loop-in is a feature you'd like, feel free to update the issue to a feature request for multi-loop-in?

**Comment by Talkless** [comment]
Thanks for clarification @carlaKC .
Yes it seems what I want is multi-loop-in. Maybe I'll just create new issue after closing this one.
