### ISSUE TITLE
Add support for multi-loop-in to refill multiple channels with single on-chain transaction

### ISSUE THREAD

**Issue by Talkless** [lightninglabs/loop#290]
It kinda "hurts" when you see that you would need to perform multiple loop-ins to refill multiple channels, if most of your funds are on the remote side and can't spend any more.

I guess for now I would leave smaller channels as it is, just refill bigger ones, conserving blockchain space (and fees for myself and others).

**Comment by alexbosworth** [comment]
Multi-loop in is now supported, but if you want to allow for multiple peers to be selected please create a new feature request and this will be gated on a future LND upgrade to allow for selecting multiple last hop peers.

**Comment by Talkless** [comment]
@alexbosworth could you please clarify a bit. If you can't select last hop, what does that "multi-loop" do then? It will choose automatically and refill multiple channel by trial/error?

**Comment by alexbosworth** [comment]
Yes it will choose automatically

An existing option after the loop in is completed is to use circular rebalancing to distribute the liquidity to your desired distribution

**Comment by Talkless** [comment]
> Yes it will choose automatically

That's good enough, thanks for explanation!
