### ISSUE TITLE
Loop Out got stuck?

### ISSUE THREAD

**Issue by rene78** [lightninglabs/loop#296]
Wanted to be stingy and used Loop Out with the following parameters:
![Unbenannt](https://user-images.githubusercontent.com/36115705/93262263-35f27200-f7a4-11ea-84b9-dfa993d268a8.png)
For 10 hours the status is _**Initiated**_ already.
![image](https://user-images.githubusercontent.com/36115705/93262390-74882c80-f7a4-11ea-81a0-0da0f55fa1b0.png)
**Do I need more patience or did I completely mess up?**

**Comment by joostjager** [comment]
It looks like the server swept back the htlc on-chain after it expired, so the swap has failed permanently. Your off-chain payment should've been cancelled back.

Do you have log files for `loopd`?

**Comment by rene78** [comment]
Thanks for your reply, @joostjager! Yes, shortly after writing the post above the status changed to **_Failed_** and my off-chain balance got updated. Won't change the default **_Sweep Confirmation target_** in the future.
![image](https://user-images.githubusercontent.com/36115705/93302719-b9d74900-f7fa-11ea-8102-3cfc7576cb8b.png)

**Comment by alexbosworth** [comment]
The on-chain sweep target would not have impacted a sweep that failed before it got to the on-chain sweep step

There are potentially more failure details that can be revealed that may be hidden by the UI, this is something that could be requested of RTL to expose
