### ISSUE TITLE
I can't idenpendently verify the signing PGP key

### ISSUE THREAD

**Issue by Kixunil** [lightninglabs/loop#308]
I'd like to verify the signing PGP key of @alexbosworth however, it seems to be published on GitHub only. The keybase account `alexbosworth` contains two different keys. No key seems to be published on Twitter.

It'd be great to publish the signing key on Twitter or connect the key **and** Twitter with Keybase, so that I can verify the authenticity better than just trusting GitHub.

**Comment by alexbosworth** [comment]
Steps to verify via Twitter:

1. Click on Yalls
2. Click on About
3. Click on Key icon below "Alex Bosworth"

I do not use any keybase signing keys to sign anything and I wouldn't trust anything I appear to have signed with them. Their software doesn't allow for my actual keys to be used

**Comment by Kixunil** [comment]
Thanks! I do use my actual keys with keybase but I think they moved away from such model since I created the account.

**Comment by alexbosworth** [comment]
> Thanks! I do use my actual keys with keybase but I think they moved away from such model since I created the account.

The way that I generate my keys, I don't actually keep any access to the raw key material so that makes it difficult to use with other services that need that raw key

**Comment by Kixunil** [comment]
Yeah, I did it similarly and had to sign manually.
