### ISSUE TITLE
Please provide source of loop service

### ISSUE THREAD

**Issue by ratpoison4** [lightninglabs/loop#314]
I see one immediate practical use-case and one fundamental reason to do it.

If two people not trusting each other want to swap on-chain and off-chain funds one of them could run Loop service and another run `loop in` or `loop out` depending on the direction. Currently it is not possible, because Loop service is provided as a service, not as software, so people can swap only with the official service, not between themselves.

Fundamental reason is that if in the future Lightning Labs is forced to close its Loop service (e.g. the state makes it illegal) then in case code is not available it means the end of the product. If code is available be sure somebody else runs another instance maybe in onion. I think this is the same reason why Wasabi team opensourced their coordinator software which is also not needed by end clients.

**Comment by Kixunil** [comment]
Another practical reason is that not having the source of service available makes it impossible to do integration testing of loop using regtest.

Since I respect the choice to keep it closed, I'd like to ask at least for providing a crippled binary that is limited to regtest (possibly with more restrictions). I don't care much about the code, just that it can be tested.

**Comment by guggero** [comment]
@Kixunil while providing the full source of the backend service likely isn't an option (at least near-term), providing a way to integration test Loop applications is on our list of priorities: https://github.com/lightninglabs/loop/issues/276

**Comment by Kixunil** [comment]
Awesome, I'm very happy to hear that! It'll allow me to integrate loop sooner without fear of breaking stuff or spending lot of time on waiting for testnet blocks to be mined. :)

**Comment by Roasbeef** [comment]
Closing as we're tracking this with #276
