### ISSUE TITLE
Connection errors in testnet

### ISSUE THREAD

**Issue by gnasr** [lightninglabs/loop#315]
Hi, i was working with loop early this morning in testnet, and everything was ok, been doing loop outs in testnet for the whole week, but suddenly it stopped working and all the rpc calls to loopd return the same error:

loopd and loop version: loop version 0.9.0-beta

```
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed
```

example:
testnet
```
# loop terms
 Loop Out
--------
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed
Loop In
------
rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection closed
```

mainnet works
```
# loop terms
Loop Out
--------
Amount: 250000 - 60000000
Cltv delta: 100 - 400
Loop In
------
Amount: 250000 - 60000000
```

I tried restarting my testing instance, and also rebuilt it from scratch but the errors seems to be external to my loopd server

also, do you have a status page for loop service? it would be nice to have

**Comment by alexbosworth** [comment]
Can you try again now?

**Comment by gnasr** [comment]
It's working, thanks

**Comment by guggero** [comment]
Seems to have been an infrastructure issue on our side, closing the issue since it looks to be resolved now.
