### ISSUE TITLE
[loop] rpc error: code = DeadlineExceeded desc = context deadline exceeded

### ISSUE THREAD

**Issue by jogc** [lightninglabs/loop#322]
I'm currently getting this when issuing any loop command. Mainnet. Restarting loopd does not help.

**Comment by realspencerdupre** [comment]
Same here, was working yesterday.

**Comment by realspencerdupre** [comment]
Looks like https://github.com/lightninglabs/loop/issues/42 this issue has returned.

**Comment by alexbosworth** [comment]
This should now be resolved

**Comment by sotarules** [comment]
Friend s on loop 0.11.2-beta I'm getting this problem today:
```
root@router:~# loop in 290000
Max swap fees for 290000 sat Loop In: 144931 sat
CONTINUE SWAP? (y/n), expand fee detail (x): y
[loop] rpc error: code = Unknown desc = cannot initiate swap: rpc error: code = DeadlineExceeded desc = context deadline exceeded
root@router:~# loop --version
loop version 0.11.2-beta commit=
root@router:~#
```
I'm running LND version 0.12.0-beta.rc2 commit=v0.12.0-beta.rc2.  Everything is up-to-date.

**Comment by brandonshope** [comment]
New install and I am seeing this error. Any insight in to what causes this error?

mainnet

[loop] rpc error: code = Unknown desc = cannot initiate swap: rpc error: code = DeadlineExceeded desc = context deadline exceeded
loop@raspberrypi:~ $ loop --version
loop version 0.11.4-beta commit=
loop@raspberrypi:~ $ 

lnd LND 0.11.1-beta
raspiblitz v1.6.3

**Comment by guggero** [comment]
The error means something is taking too long. This can either be due to a network timeout or some other slow component. What action did you take before you got that error? Some more logs would be helpful too.

**Comment by brandonshope** [comment]
Thanks @guggero. That pointed me in the right direction. Apparently, the added latency from TOR is not compatible with loop. Error went away after disabling TOR.

**Comment by pysiak** [comment]
Is there a way for it to work on tor? Increase some timeout?
