### ISSUE TITLE
Unimplemented desc = unknown service lnrpc.Lightning

### ISSUE THREAD

**Issue by fenngineering** [lightninglabs/loop#329]
I'm experiencing the below issue when connecting loop to lnd, as you can see in log out put after the loopd command, it connects to lnd successfully but it fails with `Unimplemented desc = unknown service lnrpc.Lightning` 

Any help with this is much appreciated.
Thanks 

**Installation of loop**
`wget https://github.com/lightninglabs/loop/releases/download/v0.11.2-beta/loop-freebsd-amd64-v0.11.2-beta.tar.gz`
`tar -xvf loop-freebsd-amd64*`
`install -m 0755 -o root -g wheel loop-freebsd-amd64*/* /usr/local/bin`

**Command**
`loopd --lnd.macaroondir=/var/db/lnd/data/chain/bitcoin/mainnet --lnd.tlspath=/var/db/lnd/tls.cert --server.proxy=localhost:9050`

**Error**
`root@bitcoin-node:~ # lncli -lnddir "/var/db/lnd" unlock
Input wallet password:
lnd successfully unlocked!`

`root@bitcoin-node:~ # loopd --lnd.macaroondir=/var/db/lnd/data/chain/bitcoin/mai
nnet --lnd.tlspath=/var/db/lnd/tls.cert --server.proxy=localhost:9050
2021-01-21 12:39:50.543 [INF] LOOPD: Version: 0.11.2-beta commit=
2021-01-21 12:39:50.544 [INF] LNDC: Creating lnd connection to localhost:10009
2021-01-21 12:39:50.544 [INF] LNDC: Connected to lndloopd exited with an error: lnd compatibility check failed: unable to get info for lnd node: rpc error: code = Unimplemented desc = unknown service lnrpc.Lightning`

**Environment**
`FreeBSD 11.3-RELEASE-p14 amd64`
**Versions**
`root@bitcoin-node:~ # lnd --version
lnd version 0.12.0-beta.rc6 commit=v0.12.0-beta.rc6`

`root@bitcoin-node:~ # loop --version
loop version 0.11.2-beta commit=`

`root@bitcoin-node:~ # bitcoind --version
Bitcoin Core version v0.20.1.0-g7ff64311bee570874c4f0dfa18f518552188df08`

**Configs**

**lnd.conf**
[Application Options]
lnddir=/var/db/lnd
externalip=x.x.x.x
alias=blah
listen=localhost
restlisten=127.0.0.1:8080
rpclisten=127.0.0.1:10009
tlsextraip=0.0.0.0

[Bitcoin]
bitcoin.active=1
bitcoin.mainnet=1
bitcoin.node=bitcoind
bitcoin.basefee=1000
bitcoin.feerate=100
bitcoin.timelockdelta=40

[Bitcoind]
bitcoind.dir=/var/db/bitcoin
bitcoind.rpcuser=xxxxx
bitcoind.rpcpass=xxxxx
bitcoind.zmqpubrawblock=tcp://127.0.0.1:28332
bitcoind.zmqpubrawtx=tcp://127.0.0.1:28333

[tor]
tor.active=1
tor.socks=localhost:9050
tor.dns=soa.nodes.lightning.directory:53
tor.control=localhost:9051
tor.v3=1

**bitcoind.conf**
externalip=x.x.x.x
server=1
txindex=1.
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
server=1
txindex=1
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
rpcallowip=127.0.0.1
rpcbind=127.0.0.1
rpcuser=xxxxx
rpcpassword=xxxxx.

**Comment by alexbosworth** [comment]
Can you confirm that lnd is unlocked and that it was built with the required RPC tags?

**Comment by fenngineering** [comment]
Hi @alexbosworth yes its unlocked as above in the **Error** section

**Comment by fenngineering** [comment]
@alexbosworth 
lnd was installed like this...
`wget https://github.com/lightningnetwork/lnd/releases/download/v0.12.0-beta.rc6/lnd-freebsd-amd64-v0.12.0-beta.rc6.tar.gz`
`tar -xvf lnd-freebsd-amd64*`
`install -m 0755 -o root -g wheel ~/lnd-freebsd-amd64*/* /usr/local/bin`

i used a pre build binary.

**Comment by carlaKC** [comment]
There is a brief moment between lnd being unlocked and the main rpc server registering where you could be running into this error. If you unlock lnd, call getinfo using `lncli` (just to sanity check that it's working) and then start up loop do you still run into the error?

We recently merged a change in #327 to make loop wait for lnd to be ready, which will be included in our next release. If the race for server registration is what's happening here, that will address it.

**Comment by fenngineering** [comment]
@carlaKC thanks for your help. When I run the below I seem to get an error:-
`root@bitcoin-node:~ # lncli --network=mainnet getinfo
[lncli] could not load global options: unable to decode macaroon: cannot determine data format of binary-encoded macaroon`

What might be the cause of this?

**Comment by carlaKC** [comment]
> `root@bitcoin-node:~ # lncli --network=mainnet getinfo [lncli] could not load global options: unable to decode macaroon: cannot determine data format of binary-encoded macaroon`

Looks like there's an issue with the macaroons you're using?  I see you've opened lightningnetwork/lnd/issues/4949 on lnd so going to close this issue since the root issue is not being able to query lnd.
