### ISSUE TITLE
swapinfo REST RPC failure

### ISSUE THREAD

**Issue by saloppe73** [lightninglabs/loop#341]
I'm using the REST RPC call to get a swapinfo. I encoded the id as url safe base64 like described at the docs but I get an error:

`{'error': 'error parsing swap hash: invalid hash length of 64, want 32', 'code': 2, 'message': 'error parsing swap hash: invalid hash length of 64, want 32', 'details': []}`

I'm using 11.1-beta. 
Any hints? Maybe my brain is frozen after 30 hours. Thanks

**Comment by guggero** [comment]
You're probably taking the hex encoded ID and directly encode it as base64 which results in a string that's too long.
You instead need to hex decode the ID to get the raw bytes (likely a `Buffer` in JS) and then re-encode those raw bytes as base64.

**Comment by saloppe73** [comment]
I take the id of the loopIn/Out response. Can I get a python snippet how to convert the id so I can use it as parameter for the swapinfo call? Thanks.

**Comment by guggero** [comment]
I haven't used the REST API in a while. What does the ID look like there? Is it base64 already?
Then you probably only need to convert it from non-URL-safe to URL-safe:
```
rawID = base64.b64decode(responseID)
urlSafeID = base64.urlsafe_b64encode(rawID)
```

If it's hex, just replace the first line with:
```
rawID = responseID.decode("hex")
```

I'm not a Python programmer, this is just what I got from Google... Hope it helps.

I'm closing the issue as I'm pretty sure there's nothing wrong with the REST API (apart from maybe not being too developer friendly). Feel free to comment again if you aren't able to get it working.

**Comment by saloppe73** [comment]
Thanks. Just realized there is already a field 'id_bytes' at the loopIn/Out response. You have to take this value as parameter, not the id value.
