### ISSUE TITLE
Simplify loop fee details

### ISSUE THREAD

**Issue by justinpobrien** [lightninglabs/loop#346]
**Problem**
Users find the fees confusing and intimidating. We ought to improve the clarity of the fees if possible.

Here's what we show currently when you attempt to Loop Out:
```
Max swap fees for 1000000 sat Loop Out: 1717920 sat
Regular swap speed requested, it might take up to 30m0s for the swap to be executed.
CONTINUE SWAP? (y/n), expand fee detail (x): x

Estimated on-chain sweep fee:        16963 sat
Max on-chain sweep fee:              1696300 sat
Max off-chain swap routing fee:      20010 sat
Max no show penalty (prepay):        30000 sat
Max off-chain prepay routing fee:    610 sat
Max swap fee:                        1000 sat
```
Compare this to the experience using Boltz:

![image](https://user-images.githubusercontent.com/10817083/109591296-5b084200-7ab1-11eb-980a-665331f756dc.png)

This complexity prevents users from even attempting to use the service and instead they default to getting inbound liquidity in the easiest way possible (and aren't necessary knowledgeable enough to know that not all inbound liquidity is the same):
![image](https://user-images.githubusercontent.com/10817083/109591505-b9cdbb80-7ab1-11eb-829b-1b716d2e087a.png)

**Comment by alexbosworth** [comment]
Simplification ideas:

- Remove the destination public key as it is not usable
- Note the maximum routing fee PPM rate to appraise of routing fee costs
- Note that fees may exceed the estimation due to variable chain fees, remove max
- Only show estimated fee in normal mode, require expansion to see more details

**Comment by justinpobrien** [comment]
Ok modified #344 since there is strong overlap. This is now a duplicate issue
