### ISSUE TITLE
Loop In: real server error is swallowed

### ISSUE THREAD

**Issue by guggero** [lightninglabs/loop#355]
Referencing https://github.com/lightninglabs/lightning-terminal/issues/198.

The user sees the error message:
```
2021-03-10 08:30:40.567 [ERR] LOOPD: Loop in: cannot initiate swap: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```

Even though the server returns the following error code (payment probe failing due to timeout):
```
2021-03-10 08:30:41.367 [ERR] NAUT: Swap b044bd3xxxxx initiation error: FailedPrecondition (target unreachable)
```

It seems somewhere we swallow the actual error code.

**Comment by andrerfneves** [comment]
@guggero in cases like this what is the best approach to resolve this? Smaller loop in amounts? Are these bad channels?

**Comment by andrerfneves** [comment]
I've tried with quite a few diff channels and different amounts. All Loop Ins error out like this with the deadline exceeded call.

**Comment by guggero** [comment]
That would've been my suggestion, to just try again a few times with different amounts and different channels. I just tried a loop in myself and it seems to work in general. Could be you have a peer between you and the pool server that's not properly forwarding the probe payment. Unfortunately this is quite hard to debug.
