### ISSUE TITLE
Loop out failed but funds not returned to channel

### ISSUE THREAD

**Issue by SteveD41** [lightninglabs/loop#382]
I was attempting to perform a loop out and it failed a few times and I re-attempted each time with a lower amount (it seems to work eventually with amounts < 500,000 sats).

I decided to see what the upper limit was and  tried a few times each time reducing the amount to see what the maximum amount was that would be processed.

I issued a request for 902727 sats and waited and monitored loopd and like my previous attempts it reported failure HOWEVER this time the funds have not been returned to my channel and seemingly have disappeared with the fairies.

This is the loopd output (!! note the final line is a first I have seen during previous failed payments!!)

"2021-05-02 10:44:24.003 [INF] LOOP: 6f476f Server update: FAILED_OFF_CHAIN_TIMEOUT received, timestamp: 2021-05-02 10:44:23.916045259 +0100 BST
2021-05-02 10:44:24.003 [INF] LOOP: 6f476f swap subscription: server finished serving updates
2021-05-02 10:44:24.007 [INF] LOOP: Received block 681508
2021-05-02 10:44:24.007 [INF] LOOP: 6f476f Checking preimage reveal height 681586 exceeded (height 681508)
2021-05-02 10:44:25.833 [INF] LOOP: 6f476f Payment 1aa4a01efcea7b3e344027681757c3d684e4f02e7e93400b9bc49c27b64d0f9e: state=IN_FLIGHT, inflight_htlcs=0, inflight_amt=0 mSAT
2021-05-02 10:44:25.853 [INF] LOOP: 6f476f Payment 1aa4a01efcea7b3e344027681757c3d684e4f02e7e93400b9bc49c27b64d0f9e: state=FAILED
2021-05-02 10:44:25.853 [INF] LOOP: 6f476f Failed prepayment: payment failed
2021-05-02 10:44:25.853 [INF] LOOP: 6f476f Wait for server pulling off-chain payment(s)2021-05-02 10:44:24.003 [INF] LOOP: 6f476f Server update: FAILED_OFF_CHAIN_TIMEOUT received, timestamp: 2021-05-02 10:44:23.916045259 +0100 BST
2021-05-02 10:44:24.003 [INF] LOOP: 6f476f swap subscription: server finished serving updates
2021-05-02 10:44:24.007 [INF] LOOP: Received block 681508
2021-05-02 10:44:24.007 [INF] LOOP: 6f476f Checking preimage reveal height 681586 exceeded (height 681508)
2021-05-02 10:44:25.833 [INF] LOOP: 6f476f Payment 1aa4a01efcea7b3e344027681757c3d684e4f02e7e93400b9bc49c27b64d0f9e: state=IN_FLIGHT, inflight_htlcs=0, inflight_amt=0 mSAT
2021-05-02 10:44:25.853 [INF] LOOP: 6f476f Payment 1aa4a01efcea7b3e344027681757c3d684e4f02e7e93400b9bc49c27b64d0f9e: state=FAILED
2021-05-02 10:44:25.853 [INF] LOOP: 6f476f Failed prepayment: payment failed
****2021-05-02 10:44:25.853 [INF] LOOP: 6f476f Wait for server pulling off-chain payment(s)****"

**Expected behavior**

**Actual behavior**

**To reproduce**

**System information**

Loop monitor log (usually the monitor will report the failure after loopd reports it but this time nothing)

2021-05-02T10:22:51+01:00 LOOP_OUT FAILED (FAILURE_REASON_OFFCHAIN) 0.01128409 BTC - bc1q70kr2ep2r0qudxg2l2ql38f2uvjjdxdsgvk86r84xlyg2lyt4jpqv6nsca (cost: server 0, onchain 0, offchain 0)
2021-05-02T10:24:03+01:00 LOOP_OUT INITIATED 0.00902727 BTC - bc1qmwxnmy0np9rl877ugq7szqg8exvftw8epq0n5ahwghgepwup0sas2qt33s

**Comment by SteveD41** [comment]
I did put entries for expected/actual behaviour ^ system information when creating the issue but it looks like they did not get included.

**Expected behaviour**

It would work

**Actual behaviour**

My funds have disappeared

**System information**

Running on RasPi4 with a Raspiblitz build. Running loop out via terminal issuing loop out to a specific wallet address

**Comment by SteveD41** [comment]
I have done a lncli listpayments and I can see the failed payment BUT when I do a lncli channelbalance the balance is now only 270201 and the original payment was 902727 so if the funds had been returned then lncli channelbalance would report at least a balance that was equal to the failed payment but it does not it reports a lower balance (no other transaction have occurred since the failed payment).

**Comment by SteveD41** [comment]
This is the output from listpayments

   {
            "payment_hash": "1aa4a01efcea7b3e344027681757c3d684e4f02e7e93400b9bc49c27b64d0f9e",
            "value": "30000",
            "creation_date": "1619947443",
            "fee": "0",
            "payment_preimage": "0000000000000000000000000000000000000000000000000000000000000000",
            "value_sat": "30000",
            "value_msat": "30000000",
            "payment_request": "lnbc300u1psgumanpp5r2j2q8huafanudzqya5pw47r66zwfupw06f5qzumcjwz0djdp70qdq2wpex2urp0ycqzxgxq97zvuqrzjqgwf02g2gy0l9vgdc25wxt0z72wjlfyagxlmk54ag9hyvrdsw37s6zs6syqqrmcqqyqqqqqqqqqqqqqq9qrzjqgwf02g2gy0l9vgdc25wxt0z72wjlfyagxlmk54ag9hyvrdsw37s6z34hyqqdlcqqyqqqqqqqqqqqqqq9qrzjqgwf02g2gy0l9vgdc25wxt0z72wjlfyagxlmk54ag9hyvrdsw37s6zs79qqqz4cqqqqqqqqqqqqqqqqq9qsp5djz7yp74dmne5geczrejks8vrr557np5cv3w4d6tz62dcpg5t5kq9qyyssql8chp6m3vyaev5l3wv7rtg8gux8pg4mpa33z0f4gvy52rm4tn04heanuktl6edc55qhqn74vnykknyxvj0ml3qvew5hmlcdf34x2wlspk69ru8",
            "status": "FAILED",
            "fee_sat": "0",
            "fee_msat": "0",
            "creation_time_ns": "1619947443932528616",
            "htlcs": [
                {
                    "status": "FAILED",
                    "route": {
                        "total_time_lock": 681943,
                        "total_fees": "204",
                        "total_amt": "30204",
                        "hops": [
                            {
                                "chan_id": "747798748902260737",
                                "chan_capacity": "3660000",
                                "amt_to_forward": "30195",
                                "fee": "9",
                                "expiry": 681799,
                                "amt_to_forward_msat": "30195100",
                                "fee_msat": "9059",
                                "pub_key": "028a8e53d70bc0eb7b5660943582f10b7fd6c727a78ad819ba8d45d6a638432c49",
                                "tlv_payload": true,
                                "mpp_record": null,
                                "custom_records": {
                                }
                            },
                            {
                                "chan_id": "695899601111613441",
                                "chan_capacity": "10000000",
                                "amt_to_forward": "30000",
                                "fee": "195",
                                "expiry": 681749,
                                "amt_to_forward_msat": "30000000",
                                "fee_msat": "195100",
                                "pub_key": "02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844",
                                "tlv_payload": true,
                                "mpp_record": null,
                                "custom_records": {
                                }
                            },
                            {
                                "chan_id": "748191274492231681",
                                "chan_capacity": "40000000",
                                "amt_to_forward": "30000",
                                "fee": "0",
                                "expiry": 681709,
                                "amt_to_forward_msat": "30000000",
                                "fee_msat": "0",
                                "pub_key": "021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d",
                                "tlv_payload": true,
                                "mpp_record": null,
                                "custom_records": {
                                }
                            },
                            {
                                "chan_id": "729064170168188928",
                                "chan_capacity": "30000",
                                "amt_to_forward": "30000",
                                "fee": "0",
                                "expiry": 681709,
                                "amt_to_forward_msat": "30000000",
                                "fee_msat": "0",
                                "pub_key": "03fb2a0ca79c005f493f1faa83071d3a937cf220d4051dc48b8fe3a087879cf14a",
                                "tlv_payload": true,
                                "mpp_record": {
                                    "payment_addr": "6c85e207d56ee79a233810f32b40ec18e94f4c34c322eab74b1694dc05145d2c",
                                    "total_amt_msat": "30000000"
                                },
                                "custom_records": {
                                }
                            }
                        ],
                        "total_fees_msat": "204159",
                        "total_amt_msat": "30204159"
                    },
                    "attempt_time_ns": "1619947445169410960",
                    "resolve_time_ns": "1619948665813158079",
                    "failure": {
                        "code": "INCORRECT_OR_UNKNOWN_PAYMENT_DETAILS",
                        "channel_update": null,
                        "htlc_msat": "0",
                        "onion_sha_256": null,
                        "cltv_expiry": 0,
                        "flags": 0,
                        "failure_source_index": 4,
                        "height": 681506
                    },
                    "preimage": null
                }
            ],
            "payment_index": "154",
            "failure_reason": "FAILURE_REASON_INCORRECT_PAYMENT_DETAILS"
        }
    ],
    "first_index_offset": "1",
    "last_index_offset": "154"
}

**Comment by SteveD41** [comment]
I can see from my lightning manager that I have an open HTLC with a block height of about 3 days away so would I be correct in assuming that the channel balance will reflect the HTLC at that date ?

**Comment by carlaKC** [comment]
> This is the output from listpayments

From this output + double checking the logs on our side, I can see that the server canceled the swap prepayment & invoice when the swap timed out on chain, as it should do. 

> I can see from my lightning manager that I have an open HTLC with a block height of about 3 days away so would I be correct in assuming that the channel balance will reflect the HTLC at that date ?

Indeed, the HTLC should be failed back when it expires and all funds will be released. Looks like your prepayment was canceled back, so this active payment should be for the rest of the swap amount. Could you confirm the amount for the pending htlc/ status of your swap payment in listpayments for me? All seems to be in order, but no harm double checking.

**Comment by SteveD41** [comment]
I just checked the HTLC and it has 875341 sats in it

**Comment by carlaKC** [comment]
> I just checked the HTLC and it has 875341 sats in it

That's the swap payment then. The server has already canceled back, but it's possible that a node along the route is down/taking long to cancel back. Once it times out funds will be returned to local balance, nothing out of the ordinary.
