### ISSUE TITLE
Loop Out Failed, Sats still missing

### ISSUE THREAD

**Issue by hypernode123** [lightninglabs/loop#416]
Started a loop out here:

``` 2021-08-26T09:57:32+01:00 LOOP_OUT INITIATED 0.00495 BTC - xxx ```

There is still an active HTLC for it. The funds are not in the channel and I have not received them on-chain.

Loopd daemon was running all the time, no crashes, node was up all the time as well.

Today I restarted Loopd, this are the last logs:

```xxx
```

Payment tracking:

```
lncli  trackpayment xxx
xxx
```

Do I need to worry about my sats being lost?

**Comment by carlaKC** [comment]
Redacted the logs, will get somebody with perms to delete the issue. In future feel free to send sensitive info through on our community slack directly to whoever is helping you out.
