### ISSUE TITLE
tor.Dial() missing skipProxyForClearNetTargets flag

### ISSUE THREAD

**Issue by hieblmi** [lightninglabs/loop#427]
https://github.com/lightninglabs/loop/blob/91ad53a811b3f0a349006b85bf12c11f2f3097ac/swap_server_client.go#L695-L698
misses parameter `skipProxyForClearNetTargets` according to function definition https://github.com/lightningnetwork/lnd/blob/a6f22c6185c43698d310f28fc08959c17f77748a/tor/tor.go#L68 which was recently updated in this commit: https://github.com/lightningnetwork/lnd/commit/1ebc3b82c8fa316e6c1f975ab0524eeeb4256148

**Comment by yyforyongyu** [comment]
I think we are using an older version of `lnd` here?

**Comment by hieblmi** [comment]
Doesn't commit https://github.com/lightningnetwork/lnd/commit/1ebc3b82c8fa316e6c1f975ab0524eeeb4256148 say it was introduced in v0.14.0-beta.rc1 which loop's go.mod is pulling?https://github.com/lightninglabs/loop/blob/139eac6febd0796a4f069a23324a543a28ef0436/go.mod#L15

I am probably missing something here.

**Comment by yyforyongyu** [comment]
> Doesn't commit [lightningnetwork/lnd@1ebc3b8](https://github.com/lightningnetwork/lnd/commit/1ebc3b82c8fa316e6c1f975ab0524eeeb4256148) say it was introduced in v0.14.0-beta.rc1 which loop's go.mod is pulling?
> 
> https://github.com/lightninglabs/loop/blob/139eac6febd0796a4f069a23324a543a28ef0436/go.mod#L15
> 
> I am probably missing something here.

Yeah we do for the master branch, not for the commit you linked tho. We've upgraded in this [commit](https://github.com/lightninglabs/loop/commit/2c6e035235c7adcabb825ec611163db6413499af).

**Comment by hieblmi** [comment]
I see, thanks for the explanation. Closing this.
