### ISSUE TITLE
Loop setparams: swap fee PPM must be non-zero

### ISSUE THREAD

**Issue by sotarules** [lightninglabs/loop#479]
**Expected behavior**

Friends, I have some channels being managed by autoloop but after doing some initial balancing, many are now disqualified.

```
{
    "loop_out": [
    ],
    "loop_in": [
    ],
    "disqualified": [
        {
            "channel_id": "772583939960995840",
            "pubkey": null,
            "reason": "AUTO_REASON_PREPAY"
        },
        {
            "channel_id": "727345633609580545",
            "pubkey": null,
            "reason": "AUTO_REASON_LIQUIDITY_OK"
        },
        {
            "channel_id": "727090546821365761",
            "pubkey": null,
            "reason": "AUTO_REASON_LIQUIDITY_OK"
        },
        {
            "channel_id": "733005919405408257",
            "pubkey": null,
            "reason": "AUTO_REASON_PREPAY"
        },
        {
            "channel_id": "772686194551422977",
            "pubkey": null,
            "reason": "AUTO_REASON_PREPAY"
        },
        {
            "channel_id": "733522689825767425",
            "pubkey": null,
            "reason": "AUTO_REASON_LIQUIDITY_OK"
        }
    ]
}
```
As you can see the disqualification reason is ```AUTO_REASON_PREPAY```.  As part of my ongoing experimentation, I want to relax this constraint to allow the system to go forward with the loop out irrespective of ```AUTO_REASON_PREPAY``` so I'm trying to set the limits.

```loop setparams --maxprepay 20000``` command should set prepayment maximum for no-show.

**Actual behavior**

```[loop] rpc error: code = Unknown desc = swap fee PPM must be non-zero```

I've tried to set a bunch of different parameters, but many of them cause the system to issue this same message.  I've searched everywhere but I cannot find a good guide on all of the constraints on the parameters and how to set them.  If there is some sequence I need to do that would be good information to have.  Also, an example of a several example configurations for people that have different tolerances regarding costs, including how to set all of the parameters.

Examples: 

- Tightwad configuration
- Conservative configuration
- Liberal Configuration
- Test Configuration (guaranteed to swap almost always)

**To reproduce**

I can reproduce 100% of the time on 0.18.0-beta.

**System information**

Using stand-alone loop through command line interface.
Loop version is 0.18.0-beta
I am building from go using go install ./..
This is on a Qotom i5 Celeron machine running Ubuntu Impish.

**Comment by hieblmi** [comment]
I think there was a auto-loop overhaul in the meantime so please feel free to reopen the issue if this persists.
