### ISSUE TITLE
Loop out causing OOM kill in LND

### ISSUE THREAD

**Issue by mrmcbitcoin** [lightninglabs/loop#491]
My lnd crashed with an oom-kill yesterday. The issue is in loopd which I was running in Lightning Terminal to get inbound liquidity. I can shut down LIT and run loopd manually to reproduce the oom-kill behavior.

**Expected behavior**

loopd runs without crashing LND and my node has the needed in/out liquidity.

**Actual behavior**

loopd caused LND to exhaust all memory and never finishes

**To reproduce**

Run loop out five or six times, maybe not being patient and waiting for loops to finish. If I need to get more info I can run loopd again and get the log before it crashes.

**System information**
lncli version 0.14.3-beta commit=v0.14.3-beta
lightning-terminal-linux-amd64-v0.6.7-alpha
loop-linux-amd64-v0.18.0-beta
Fedora 36 Server am64
Celeron dual core CPU with 8GB DDR3 memory 1TB 7200 RPM HDD

Connected through LIT to create loop out but problem exists when running poold manually. There was a failed loop at some point, but four or five have run successfully since I've been using the tool.

**Comment by mrmcbitcoin** [comment]
I think I have this resolved. I was messing around with routerrpc trying to get less failures when this issue started. Setting all of the routerrpc.* settings to default seems to have fixed this.

**Comment by guggero** [comment]
Interesting... Sounds like you might have run into an edge case where the pathfinding algorithm just never stops exploring the graph.
Would you mind sharing the settings you had so we can perhaps set better limits?

**Comment by guggero** [comment]
Ah, I think `routerrpc.aprioriweight=0` is what caused this in combination with `routerrpc.minrtprob=0.4`. If my interpretation is correct, this means the algorithm will assign a success probability of 0 to routes it has no data on but will require a minimum probability of 40% to actually attempt a route. And assuming your node doesn't have that many previous payments to rely on, it basically means there were no routes to be found and the Dijkstra search algorithm just ran endlessly.

I'm going to open an issue in `lnd` for some better validation of these parameters (and their combined effects).
