### ISSUE TITLE
loopd logs aren't persistent 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/loop#5]

**Comment by sako0938** [comment]
I dont run lnd as a systemd service.

With lnd I usually do ```nohup lnd > /dev/null 2> /dev/null &``` since I know I am not losing any logs. It isn't the same with loopd though, I have definitely lost useful debugging logs because I didn't change my command to ```nohup loopd > loop.log 2> loop.err &```

**Comment by Roasbeef** [comment]
This was resolved with #99.
