### ISSUE TITLE
Failed loop out

### ISSUE THREAD

**Issue by Bostie** [lightninglabs/loop#510]
Hi,
Last week i was trying to do a loop out with RTL and i got a failed. I payed the fee and the 30K pre pay. The sats that was looping out came back but i did not got my fees and 30K pre pay back! I don't know if i am on the right place to ask what could be go wrong?
![IMAGE 2022-07-03 20:07:27](https://user-images.githubusercontent.com/89979525/178236436-5e54b542-e942-49bc-b394-514667ba4cec.jpg)
<img width="1167" alt="Schermafbeelding 2022-07-03 om 11 16 41" src="https://user-images.githubusercontent.com/89979525/178236438-ed2d271c-e758-4ccf-8d6d-5cb2eb2cb5f4.png">
<img width="387" alt="Schermafbeelding 2022-07-03 om 11 19 09" src="https://user-images.githubusercontent.com/89979525/178236513-7e68e5ce-30be-4731-869b-40bb72638d7b.png">
<img width="1184" alt="Schermafbeelding 2022-07-07 om 19 44 51" src="https://user-images.githubusercontent.com/89979525/178236561-2026e925-da04-4b47-9228-2fb0d48acd8a.png">

**Comment by alexbosworth** [comment]
Was this on Umbrel?

**Comment by Bostie** [comment]
Hi,
Thx for reply Alex!
I'm running on umbrel yes but did it with RTL

Grts

**Comment by alexbosworth** [comment]
Thanks for the response

It seems like this was related to https://github.com/lightninglabs/loop/issues/518 which was an issue with the app package on Umbrel and that has now been corrected

**Comment by Bostie** [comment]
Still lost 30k sats
