### ISSUE TITLE
Loop out terminated 

### ISSUE THREAD

**Issue by hiteshkanwargetbit** [lightninglabs/loop#511]
I am trying to use the loop out api to loop out the amount 

and i am trying to run the code i am getting this below error i have already added the macron and tls file

loopd exited with an error: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport:

**Comment by bhandras** [comment]
Hi @hiteshkanwargetbit 

Could you please provide a bit more information? Did you look at the cmd/loop/loopout.go to see how to parameterize the API? Did you test in regtest perhaps? Can you provide some logs?

**Comment by hieblmi** [comment]
Hi @hiteshkanwargetbit, are you still facing problems here? I am going to close this due to inactivity but please feel free to re-open if the issue persisted.
