### ISSUE TITLE
LOOP node fails to cooperative close channel

### ISSUE THREAD

**Issue by C-Otto** [lightninglabs/loop#516]
The LOOP node initiated a coop channel close. Our nodes didn't agree on a fee rate, which is why the channel is stuck in an unusable state. When I try to reconnect to LOOP, the fee negotiation process starts over, but the result is the same.

Currently, the mempool is empty:
![image](https://user-images.githubusercontent.com/344948/181878817-ac769865-7409-4957-a762-6a9d6074d092.png)

Despite of that, LOOP starts to suggest a fee of 2,717sat, whereas my node starts with a suggestion of 284sat. The process aborts once my node suggests 731sat and LOOP suggests 950sat.

Please update your settings so that realistic fee rates (that I have to pay!) are suggested.

Channel: 68a6d26ce45036547051fa9e7b6ad6b41b27741cd6d63b0c8f76b181cb7b4fd5:1

**Comment by C-Otto** [comment]
Got it working after a while (284/245 -> 665/873 -> 731).

**Comment by hieblmi** [comment]
There's been some progress on fee negotiation since the issue was opened, also improved fee negotiation is in the pipeline for v0.18.x - so closing this issue for now. Feel free to reopen if needed.
