### ISSUE TITLE
Loop out failed, charged 30,000 sats prepayment 

### ISSUE THREAD

**Issue by DLux76198** [lightninglabs/loop#518]
HI, I initiated a loop out, but it failed. I was charged 30,000 sats as a prepayment. Will this charge be reversed?

Thanks!

**Comment by alexbosworth** [comment]
can you detail more about your environment and logs etc?

**Comment by DLux76198** [comment]
Hi Alex, I use an Umbrel node and used RTL to initiate the loop out. Below is a screen grab of a failed transaction. I made three transactions, and all three failed, and I was charged prepayment of 30k for each transaction. 
 
![image](https://user-images.githubusercontent.com/101473823/183470047-fea062ed-dde7-4efd-956b-fe4f6a1f667e.png)

**Comment by alexbosworth** [comment]
can you copy and paste those id and address values out

**Comment by DLux76198** [comment]
![image](https://user-images.githubusercontent.com/101473823/183471146-5fae6f93-0228-4168-9eda-1d9d22509161.png)

**Comment by alexbosworth** [comment]
i mean copy the values as text values

**Comment by DLux76198** [comment]
Sorry, not sure how to do that. Can you instruct me on how to do this.

**Comment by alexbosworth** [comment]
i guess highlight the id value and right click, select copy, then paste that as a comment

**Comment by DLux76198** [comment]
ID
4lUlAe4iMJ9BtBunpsjJmYdhS8EqQxNVPD+RUx4A3Cg=

**Comment by DLux76198** [comment]
Is this correct?

**Comment by alexbosworth** [comment]
Great, can you do the same for the address

**Comment by DLux76198** [comment]
HTLC Address
bc1q8240saeg6j82kcfwkv3fzgwqfww2s2qyfw7q4p0ly9wdhs49tpeqpwvraq

**Comment by alexbosworth** [comment]
Great, it looks like funds were sent to that address but your client didn't complete the swap

Did you turn off the loop daemon, do you have any relevant logs on why it didn't complete the swap?

**Comment by DLux76198** [comment]
I am not sure was a loop daemon, so I didn't touch it. 

As for relevant logs, not sure where to look. If you can tell me where to look. I used RTL.

**Comment by alexbosworth** [comment]
I'm not sure exactly where on your system logs would be, but maybe contact umbrel for that

**Comment by DLux76198** [comment]
![fifth](https://user-images.githubusercontent.com/101473823/183473380-a7642b87-ca12-4055-aba4-27bdd086d821.jpg)
![fourth](https://user-images.githubusercontent.com/101473823/183473434-94c52de6-6b48-4158-9c56-f7f783b55d20.jpg)

**Comment by DLux76198** [comment]
Does this help?

**Comment by alexbosworth** [comment]
Thanks for those but it doesn't explain why your Loop daemon didn't complete the swap

**Comment by DLux76198** [comment]
Ok, I will ask Umbrel where I can find the system logs. 
Can the charges still be reversed?

**Comment by alexbosworth** [comment]
Thanks that will help see what happened

In the case that the server paid to fund the swap but you did not complete the swap, then that fee is charged. It is not charged if the swap is completed. Whether you complete the swap is depending on your client and settings and if you keep the client open for the duration of the swap. The completion time is also variable, it ranges from about 1-4 days depending on settings.

**Comment by DLux76198** [comment]
Is the setting found in my Umbrel? is it called the Loop daemon?

**Comment by alexbosworth** [comment]
Settings for the loop client are probably controlled by RTL if it makes the commands to the loop client

**Comment by DLux76198** [comment]
Do you where I can find the loop settings for RTL?

**Comment by alexbosworth** [comment]
I'm not very familiar with RTL myself

**Comment by DLux76198** [comment]
Hi Alex, I was able to access the Umbrel logs. Which parts would you like to see?

**Comment by saubyk** [comment]
Hi @alexbosworth @DLux76198 
the only settings a user can really influence on the loop out interface are:
- Sweep confirmation target
- Max routing fee
- Fast loop (yes or no)
<img width="597" alt="image" src="https://user-images.githubusercontent.com/39208279/183529343-21724a0e-14f0-4c5f-aaeb-137b2baf2a9c.png">

Would any of these have any impact on the swap not completing?

**Comment by alexbosworth** [comment]
if going by the default settings you should have about a day to keep the loop client open, so you'd want to look in the loop  logs to see if it was online during the swap and what it was saying during that time

**Comment by saubyk** [comment]
@DLux76198 going by the above response, you need to trace the Umbrel logs and look for loop daemon logs around the time you submitted the loop out.

**Comment by DLux76198** [comment]
Thanks  I will try to find this.

**Comment by howTOdoIT2** [comment]
I have the same issue,
Umbrel node that work without any issue

Initiation Time: 06/Aug/2022 15:16
Server Cost (Sats): 30,000
ID: Qqa0AfBlFBQws9hVDj7Ce7EjnCRyZLwWu0LbQXuYZFA=
HTLC Address: bc1q92y6nxxt5frfyx9n53hx8l58r3yffyarf92dxmv8ujvtte4j3ftq325aun

I wanna know who receive those 30k sats

**Comment by howTOdoIT2** [comment]
> Thanks I will try to find this.
I suppose ssh and type
`docker logs  ride-the-lightning_loop_1   -f `

**Comment by howTOdoIT2** [comment]
this is what my rtl log show:
```
2022-08-06 12:34:25.207 [INF] LOOP: 42a6b4 Payment 42a6b401f065141430b3d8550e3ec27bb1239c247264bc16bb42db417b986450: state=IN_FLIGHT, inflight_htlcs=5, inflight_amt=1522635000 mSAT
2022-08-06 12:34:28.873 [INF] LOOP: 42a6b4 Server update: HTLC_PUBLISHED received, timestamp: 2022-08-06 12:34:28.793254498 +0000 UTC
2022-08-06 12:35:57.876 [INF] LOOP: Received block 748227
2022-08-06 12:35:57.877 [INF] LOOP: 42a6b4 Checking preimage reveal height 748306 exceeded (height 748227)
2022-08-06 12:37:53.141 [INF] LOOP: 42a6b4 Server update: HTLC_CONFIRMED received, timestamp: 2022-08-06 12:37:53.061059449 +0000 UTC
2022-08-06 12:37:55.395 [INF] LOOP: 42a6b4 Payment d1abde34dbbb16d8dd49a332241e04ee23ecb9fb0a184f98728116738840903a: state=SUCCEEDED
2022-08-06 12:37:55.546 [INF] LOOP: Received block 748228
2022-08-06 12:37:55.546 [INF] LOOP: 42a6b4 Checking preimage reveal height 748306 exceeded (height 748228)
2022-08-06 12:37:56.021 [INF] LOOP: 42a6b4 Swap script confirmed on chain
2022-08-06 12:37:56.021 [INF] LOOP: 42a6b4 Htlc tx 95e0f737f6708be90de01dda938b9adb6687b43e53635edb7a7f7116504d8f9c at height 748228
2022-08-06 12:37:56.021 [INF] LOOP: 42a6b4 Htlc value: 0.01550999 BTC
2022-08-06 12:38:07.209 [ERR] LOOP: 42a6b4 Swap error: signing: rpc error: code = Unknown desc = selected sign method witness_v0 is not compatible with given pk script
2022-08-06 12:38:07.209 [INF] LOOP: 42a6b4 Loop out swap state: FailTemporary
2022-08-07 02:28:37.753 [INF] LOOP: 42a6b4 Payment 42a6b401f065141430b3d8550e3ec27bb1239c247264bc16bb42db417b986450: state=IN_FLIGHT, inflight_htlcs=4, inflight_amt=1218507617 mSAT
2022-08-07 02:28:37.908 [INF] LOOP: 42a6b4 Payment 42a6b401f065141430b3d8550e3ec27bb1239c247264bc16bb42db417b986450: state=IN_FLIGHT, inflight_htlcs=4, inflight_amt=1218507617 mSAT
2022-08-07 02:28:39.671 [INF] LOOP: 42a6b4 Payment 42a6b401f065141430b3d8550e3ec27bb1239c247264bc16bb42db417b986450: state=IN_FLIGHT, inflight_htlcs=3, inflight_amt=937544100 mSAT
2022-08-07 02:28:40.167 [INF] LOOP: 42a6b4 Payment 42a6b401f065141430b3d8550e3ec27bb1239c247264bc16bb42db417b986450: state=IN_FLIGHT, inflight_htlcs=2, inflight_amt=667662994 mSAT
2022-08-07 02:28:41.876 [INF] LOOP: 42a6b4 Payment 42a6b401f065141430b3d8550e3ec27bb1239c247264bc16bb42db417b986450: state=IN_FLIGHT, inflight_htlcs=1, inflight_amt=333831497 mSAT
2022-08-07 02:28:42.479 [INF] LOOP: 42a6b4 Payment 42a6b401f065141430b3d8550e3ec27bb1239c247264bc16bb42db417b986450: state=FAILED


```

**Comment by alexbosworth** [comment]
`Swap error: signing: rpc error: code = Unknown desc = selected sign method witness_v0 is not compatible with given pk script`

This looks like a version mismatch error, only released versions of lnd and loop are compatible with each other

**Comment by DLux76198** [comment]
Hi Alex,  I found my logs. See attached,
[RTL logs Aug 9 2021.txt](https://github.com/lightninglabs/loop/files/9293122/RTL.logs.Aug.9.2021.txt)

**Comment by howTOdoIT2** [comment]
> can you please find the version of loop daemon and lnd daemon that you are using?

 LND 0.15.0-beta 
 RTL  loop version 0.12.1-beta 
 
 
My question is : what who get those 30k sats  ? if the loop fails then will be fair to have it back

**Comment by howTOdoIT2** [comment]
> Hi Alex, I found my logs. See attached, [RTL logs Aug 9 2021.txt](https://github.com/lightninglabs/loop/files/9293122/RTL.logs.Aug.9.2021.txt)

same stuff like mine , well we do use  Umbrel  so of course , that means others will have the same issue

**Comment by alexbosworth** [comment]
The current loop version is v0.20.1-beta, potentially the old loop version is the problem, thanks for reporting the versions we are looking into what is happening with version combinations

**Comment by howTOdoIT2** [comment]
> The current loop version is v0.20.1-beta, potentially the old loop version is the problem, thanks for reporting the versions we are looking into what is happening with version combinations

ok ,  so I just loose 30k sats ?

**Comment by alexbosworth** [comment]
prepayment resolution questions aren't something that I can answer about, only information about what happened with the software exactly and how to successfully complete a swap, so for that kind of question I would try emailing support@lightning.engineering with the context and specifically the error you saw: `selected sign method witness_v0 is not compatible with given pk script` and the versions you are running

**Comment by DLux76198** [comment]
I will try writing them to see what happens. It would be nice to get a reversal of the charges for the three failed transactions.

**Comment by DLux76198** [comment]
> 

I wonder how many people using Umbrel came across this same issue?

**Comment by howTOdoIT2** [comment]
> > 
> 
> I wonder how many people using Umbrel came across this same issue?

all of them  but not many use this system to get sats out

**Comment by howTOdoIT2** [comment]
> I will try writing them to see what happens. It would be nice to get a reversal of the charges for the three failed transactions.

I contact them via email but they ask me the same thing that I already post it here...maybe they do not read  this page.
I also want a refund since the loop  failed and they have the sats in their wallet

**Comment by alexbosworth** [comment]
For Umbrel the problem seems to be related to RTL specifically, it looks like this docker configuration is using a version of the Loop client that is over a year out of date and a docker image for the app that is not from this repository, it's a third party docker image. A solution to get LND 0.15.0 support would be to update to the latest version of Loop client either separately or update the Umbrel RTL app itself

**Comment by howTOdoIT2** [comment]
> For Umbrel the problem seems to be related to RTL specifically, it looks like this docker configuration is using a version of the Loop client that is over a year out of date and a docker image for the app that is not from this repository, it's a third party docker image. A solution to get LND 0.15.0 support would be to update to the latest version of Loop client either separately or update the Umbrel RTL app itself

OK, I do understand this from the last posts but the final question : **where those 30k sats go , to umbrel, stuck  into my umbrel or to  ightning.engineering   loop server ?**

**Comment by alexbosworth** [comment]
They aren't stuck, you can look up the payment in your transaction history to see where it went, if it was successful then it went to the server. The prepayment is the charge for the server to deposit the funds on chain but it is refunded if the client successfully completes the swap and the swap fee is taken instead. If the client fails to complete the swap, the server takes the deposit fee. The client is not controlled by the server, from the server perspective complete or not complete are the only relevant variables.

**Comment by howTOdoIT2** [comment]
> From the server perspective it placed the funds on chain for the client to take them, if the client does not take them within 1-4 days, that's when it times out the swap and takes the funds.

 **Paid 30,000 Sats for prepay
August 6, 3:16:57 pm
Fee: 34 Sats** 
 the sats was sent via LN , there is no onchain TX if the  Loop Out Failed

**Comment by alexbosworth** [comment]
I believe there was an on chain tx? The funds appear to have been deposited to the address that you showed right?

**Comment by howTOdoIT2** [comment]
> I believe there was an on chain tx? The funds appear to have been deposited to the address that you showed right?

no TX was done , the sats are still  into my node  by 4days 

as you can see in the pictures that @DLux76198  post  https://user-images.githubusercontent.com/101473823/183470047-fea062ed-dde7-4efd-956b-fe4f6a1f667e.png 
STATUS: failed  no onchain TX but 30k sats were pay via LN to the server

**Comment by alexbosworth** [comment]
If you look up the address it should show some funds were sent there

**Comment by howTOdoIT2** [comment]
> If you look up the address it should show some funds were sent there
 tx id  https://oxt.me/transaction/95e0f737f6708be90de01dda938b9adb6687b43e53635edb7a7f7116504d8f9c , there is  a transaction with -0.01550999 btc but is not to my address    https://oxt.me/transaction/15bed19b51482c1beea6dcdbb8ca52286c00390efdac2678b98c6544ec78fcca   those  btc are back on the loop  server from what I see

**Comment by alexbosworth** [comment]
The way that I would read this transaction is that the funds were sent to the address and were controlled by you, but that control was only for a specific time duration of the swap, when duration expired without the client completing the swap the funds timed out back to the server

**Comment by howTOdoIT2** [comment]
> The way that I would read this transaction is that the funds were sent to the address and were controlled by you, but that control was only for a specific time duration of the swap, when duration expired without the client completing the swap the funds timed out back to the server

Ok, the swap failed so I want my 30k sats back 



thank you !

**Comment by alexbosworth** [comment]
Looks like Umbrel has updated their RTL install to no longer install the old version of Loop that is not compatible with LND 0.15

**Comment by alexbosworth** [comment]
Thanks to Umbrel for taking this on and helping users out here, a future easy way to avoid version incompatibility errors on any platform would be to use the litd packaging which includes both LND and Loop together in one released bundle, that way they shouldn't be out of step with each other.

**Comment by howTOdoIT2** [comment]
the issue is not over , we don't get the 30k sats refund !

**Comment by DLux76198** [comment]
@howTOdoIT2 You need to write to support@lightning.engineering   
I wrote them and they are working out a refund for me.

**Comment by howTOdoIT2** [comment]
> @howTOdoIT2 You need to write to [support@lightning.engineering](mailto:support@lightning.engineering) I wrote them and they are working out a refund for me.

Yes, I do see I have an email that say " I'we cc'd luke from umbrel  to handle your refunds request"  I think  those 30k sats are lost 

PS: I update the RTL and now the LOOP services   is removed :))  good fix :))  damnnnnnn
