### ISSUE TITLE
Temporary Failure

### ISSUE THREAD

**Issue by regnerlothbrog** [lightninglabs/loop#519]
I tried to Loop Out for a channel and received following error message:

The swap cannot continue due to an internal error. Manual intervention such as a restart is required.

Swap: 0020c9e3354c17d097f52cf70ece04ea31ea42ff43ac435c11120f22c20399615b8f

Can you tell me what I can do?

thank you in advance

**Comment by alexbosworth** [comment]
Did you try restarting

**Comment by regnerlothbrog** [comment]
Yes, I restarted my node or should I restart the swap? If yes, how can I restart the swap?
Sorry for this noob question 😅

**Comment by alexbosworth** [comment]
Can you look at the logs for more information

Did you try restarting loop daemon

**Comment by regnerlothbrog** [comment]
I can try it later (no access at the moment to the node) and provide you further information. 
thanks for the fast response and help

**Comment by alexbosworth** [comment]
Can you say what tool you used to instigate the swap and anything about the software you are running with your node?

**Comment by regnerlothbrog** [comment]
I‘m running an Raspiblitz Version 1.8rc4 / LND 0.15.0 and started the swap with the loop implementation from the raspiblitz

**Comment by alexbosworth** [comment]
OK also if 1.8rc4 isn't the latest version of rpiblitz then i'd update that too

**Comment by regnerlothbrog** [comment]
Ok I will do this and give you an update

**Comment by dstadulis** [comment]
might be where the error starts:

https://github.com/lightninglabs/loop/blob/master/loopout.go#L379-L390

**Comment by regnerlothbrog** [comment]
I have my sats back (don’t ask me how 😅) thank you very much for your help

**Comment by alexbosworth** [comment]
can you say anything more about what you did?

**Comment by regnerlothbrog** [comment]
I stopped the LND Deamon with lncli stop and restarted my node last night and in the morning the sats were back in my channel as local balance

**Comment by regnerlothbrog** [comment]
In Loop unser history is following message: 
The on-chain HTLC did not confirm before its expiry, or it confirmed too late for us to reveal our preimage and claim.
