### ISSUE TITLE
Trouble using loop CLI with self-signed certificate

### ISSUE THREAD

**Issue by ckritzinger** [lightninglabs/loop#537]
In my test setup, I'm running lightning-terminal with with a self-signed certificate (listening to localhost only).

The web UI works perfectly, but unfortunately, I can't seem to find any way to persuade the CLI to accept the self-signed certificate that the web UI generates.

```
$ ./loop --rpcserver=localhost:8443 --tlscertpath /path/to/tls.cert --macaroonpath /path/to/admin.macaroon quote out 100000
[loop] rpc error: code = Unavailable desc = connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown authority"
```

I've tried adding the certificate to the normal OS trust store (ubuntu in this case, so using `dpkg-reconfigure ca-certificates`) and ensured that the cert is part of `/etc/ssl/certs/ca-certificates.crt`, as per https://go.dev/src/crypto/x509/root_linux.go but no dice

Hoping that you can provide me with some advice or suggestions, even if it is just "stop wasting your time and use LetsEncrypt instead"

**Comment by guggero** [comment]
What you're doing looks correct and should work... You don't need to configure anything in your trust store if you use the `--tlscertpath`. How did you set things up in lightning-terminal? Are you sure the self-signed cert is being served by the port 8443? Maybe LiT overwrites it at startup? You need to provide both .cert and .key files to avoid the files being overwritten.
Might be worth checking what cert is really being served by running `openssl s_client -connect localhost:8443`.

**Comment by guggero** [comment]
> Also turned out that I didn't need to add the --macaroonpath argument either 

Likely because you specified a `lnd` or `litd` macaroon when you should've specified a Loop macaroon. When not using the flag the CLI falls back to the default (Loop specific) location, that's probably why it works without.
