### ISSUE TITLE
Request: Autoloop to accept `addr` parameter 

### ISSUE THREAD

**Issue by ckritzinger** [lightninglabs/loop#540]
Loop out supports the --addr parameter to directly loop out to another address.  This is very useful for our specific use case and I've been using loop out very happily on the CLI

I was really hoping to use autoloop, but unfortunately since it doesn't support a destination address, it would require two on-chain transactions to get to the right destination.

Is it possible to enable autoloop/liquidity manager to accept the following: `loop setparams --addr=XXX` ?

Two comments:

1. This would be a game changer for my use case (currently requires manual admin every day), and I would definitely use autoloop if this is enabled
2. I don't need to change the address often (possibly at all)

Or is there some alternative/workaround that I have not thought about?

**Comment by GeorgeTsagk** [comment]
Hey @ckritzinger!
Working on it :)

**Comment by ckritzinger** [comment]
Woop woop! 🎉
