### ISSUE TITLE
Latest version of loop server docker container fails to start

### ISSUE THREAD

**Issue by mrtestyboy781** [lightninglabs/loop#545]
**Problem**
Starting the latest version of loopserver [v0.9.87-beta](https://hub.docker.com/layers/lightninglabs/loopserver/v0.9.87-beta/images/sha256-08eae96d2c138de886fce6a231f78466b6df6c0b5fa4cd63d5004239e4e948a8?context=explore) gives the error 
```
Starting nautilus server got error: option `--host' uses the same long name as option `--host'
```

**To Reproduce**
```
docker run -it lightninglabs/loopserver:v0.9.87-beta daemon
```

**Comment by guggero** [comment]
Thanks for the report. I created a fix and will let you know once the new version is published (will be `v0.9.88-beta`.

**Comment by guggero** [comment]
The new version `v0.9.88-beta` was pushed to [Docker Hub](https://hub.docker.com/r/lightninglabs/loopserver/tags) just now.

**Comment by Jossec101** [comment]
It's still happening to me on v0.9.93-beta https://hub.docker.com/layers/lightninglabs/loopserver/v0.9.93-beta/images/sha256-e58eae45abbcf6f71efdf3629bbd7d127093230787d152b2f5bc80e0aefef804?context=explore @guggero

**Comment by guggero** [comment]
New version `v0.9.94-beta` is out that should now definitely fix this issue.
