### ISSUE TITLE
Validate bitcoin addresses on loop out

### ISSUE THREAD

**Issue by grunch** [lightninglabs/loop#57]
I've been using loop on my site and I constantly change between testnet and mainnet, yesterday I just made a loop out from my frontend and I didn't realize that I was connected to mainnet, so I lost 250,000 sats plus fees, I have to add address validations on my site, but it would be great if loop also have this validation, here is my `loopd view` output.
```
$ loopd view
2019-05-23 10:41:00.407 [INF] LOOPD: Version: 0.1.2-alpha commit=
2019-05-23 10:41:00.499 [INF] LNDCLIENT: Creating lnd connection to localhost:10009
2019-05-23 10:41:00.500 [INF] LNDCLIENT: Connected to lnd
2019-05-23 10:41:01.195 [INF] LNDCLIENT: Using network mainnet
2019-05-23 10:41:01.203 [INF] STORE: Checking for schema update: latest_version=1, db_version=1
OUT 43d0b82fa237612ad599de5aeb32dc98cd0262d8dcac9770776ef848304d9708
   Created: 2019-03-20 18:07:02.874154412 -0300 -03 (height 568033)
   Preimage: 2f810139aaa5993005902ef252938d67be706c0b04932882c9927308eee54b83
   Htlc address: bc1q4s8vxumrn7tuw89sg30vcazshueeyd7h67upk539hqw7fjf4e9qqv06jhy
   Uncharge channel: any
   Dest: bc1qgpyw608ur9q4r9txjuujh5l6akf6eeyv7wnv7a
   Amt: 0.0025 BTC, Expiry: 568083
   Update 0, Time 2019-03-20 18:34:11.195149367 -0300 -03, State: PreimageRevealed
   Update 1, Time 2019-03-20 18:37:05.98714838 -0300 -03, State: Success, Cost: server=0 BTC, onchain=0 BTC, offchain=0 BTC

OUT 97e9f0affd8ef45c6e17edd98807a40fc1191ceb0da82a30ead16d5040b870ef
   Created: 2019-05-22 13:06:52.129042516 -0300 -03 (height 577261)
   Preimage: ae228b5112a1f9318601d102fde4518d2447a4fbd079bc2c269f8d6eb5eb5e48
   Htlc address: bc1qsf72v7flljjhvccklelfpxu2nxyspwrzpcuv8wel95wpt4rfk42s5venjm
   Uncharge channel: any
   Dest: tb1qre3f3upldf8u42t8ta9tn43zk28tdae4q8tf2c
   Amt: 0.0025 BTC, Expiry: 577311
   Update 0, Time 2019-05-22 13:27:09.348423396 -0300 -03, State: PreimageRevealed
   Update 1, Time 2019-05-22 13:29:12.952773463 -0300 -03, State: Success, Cost: server=0.00020086 BTC, onchain=0.00017487 BTC, offchain=0.00000059 BTC
```
loop version: 0.1.2-alpha 
commit ee5f1852d652cacbcd97387f55bf30228a23b413

**Comment by alexbosworth** [comment]
Can you say what happened exactly? I'm not super clear on what you did to trigger this

**Comment by grunch** [comment]
I did it via gRPC, it's was just 
```
loopOut({
      amt: '250000',
      dest : 'tb1qre3f3upldf8u42t8ta9tn43zk28tdae4q8tf2c',
      max_swap_routing_fee: 'x',
      max_prepay_routing_fee: 'y',
      max_swap_fee: 'z',
      max_prepay_amt: 'a',
      max_miner_fee: 'b',
    })
```
those fee values I got them by loop out quote at that moment, it's not exactly a bug, but I think it would be good to avoid to let the user to use a testnet address if the loopd is running on mainnet

**Comment by alexbosworth** [comment]
Will investigate but I'm not sure how there can be an issue

For Loop Out, you would send off-chain but we wouldn't be able to get the off-chain payment unless the preimage were revealed to us on-chain

**Comment by grunch** [comment]
there's something I don't understand, I had only two loop out tx, we can see it on the loopd view output, both successfully, in the second one we can read `PreimageRevealed` but the address is a testnet address, how this could happened if the loop server was looking the preimage on mainnet, right? :confused:

**Comment by alexbosworth** [comment]
That's right, you generate the preimage and it's impossible for Loop server to take the off-chain HTLC without that preimage revealed so I would check your mainnet on-chain funds to see what happened with them

**Comment by grunch** [comment]
I have this two payments at that moment on my LND node
```
{
    "payment_hash": "77d7c70c4fc6d3492dcb0760f5dabf93ffc2d9e8fb1998a1b63138b325a9098a",
    "value": "41162",
    "creation_date": "1558541239",
    "path": [
        "03a503d8e30f2ff407096d235b5db63b4fcf3f89a653acb6f43d3fc492a7674019",
        "03864ef025fde8fb587d989186ce6a4a186895ee44a926bfc370e2c366597a3f8f",
        "02e9046555a9665145b0dbd7f135744598418df7d61d3660659641886ef1274844",
        "021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d",
        "03fb2a0ca79c005f493f1faa83071d3a937cf220d4051dc48b8fe3a087879cf14a"
    ],
    "fee": "1",
    "payment_preimage": "xxx",
    "value_sat": "41162",
    "value_msat": "41162000"
},
{
    "payment_hash": "97e9f0affd8ef45c6e17edd98807a40fc1191ceb0da82a30ead16d5040b870ef",
    "value": "228924",
    "creation_date": "1558542537",
    "path": [
        "0311cad0edf4ac67298805cf4407d94358ca60cd44f2e360856f3b1c088bcd4782",
        "02247d9db0dfafea745ef8c9e161eb322f73ac3f8858d8730b6fd97254747ce76b",
        "021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d",
        "03fb2a0ca79c005f493f1faa83071d3a937cf220d4051dc48b8fe3a087879cf14a"
    ],
    "fee": "58",
    "payment_preimage": "xxx",
    "value_sat": "228924",
    "value_msat": "228924000"
}
```
Is this node `03fb2a0ca79c005f493f1faa83071d3a937cf220d4051dc48b8fe3a087879cf14a`  the swap server? I can't get info for that node

**Comment by alexbosworth** [comment]
I see a main chain transaction associated: https://blockstream.info/tx/df266e257e593e212c0260f11282070b68ddee4bfa6d527c013567ef9a7bd712?input:0

So in theory you should control the key related to this address: https://blockstream.info/address/bc1qre3f3upldf8u42t8ta9tn43zk28tdae42ps63t

**Comment by grunch** [comment]
Not at all, as I mentioned before, I made the gRPC call to this testnet address `tb1qre3f3upldf8u42t8ta9tn43zk28tdae4q8tf2c`

**Comment by alexbosworth** [comment]
Yeah I think the issue is one of formatting

If you have a mainnet node hooked up with mainnet funds, it will do a mainnet swap with your mainnet keys

Seems like it should definitely warn you if you are using mainnet funds but specify a testnet address
