### ISSUE TITLE
Loopout Stuck for over 2 weeks with 1 sat/vB

### ISSUE THREAD

**Issue by nostrbuild** [lightninglabs/loop#639]
Hi,
I submitted a loop out under 'services' and the system assigned a 1 sat/vB which is now stuck in the mempool for over 2 weeks.
I've tried to bump fees with RBF, it sometimes appears in the receiving wallet as unconfirmed, I tried CPFP, nothing seems to work..
Is there a way I can cancel the loop out, or another way to bump the fees?

Thank You

**Comment by hieblmi** [comment]
Thanks for your report @nostrbuild. Which chain backend are you using(bitcoind, neutrino...). Could you provide us logs that show the fee bumping attempt?
Currently there is no way to cancel the loop out, you have to wait until your funds are confirmed.

**Comment by nostrbuild** [comment]
Thank you @hieblmi ! I switched to a different server for my local receiving wallet and was able to see the unconfirmed transaction. I then increased the CPFP fee to 80 sats/vB and it worked!! Finally got it out... Thank you for the reply and help!
