### ISSUE TITLE
DOCKER.md outside the docs/ directory?

### ISSUE THREAD

**Issue by FeatureSpitter** [lightninglabs/loop#640]
Wouldn't it be more consistent to have [DOCKER.md](https://github.com/lightninglabs/loop/blob/master/DOCKER.md) within the [docs](https://github.com/lightninglabs/loop/tree/master/docs) directory instead of the root of the project?

**Comment by YuckFouBTC** [comment]
This issue can be Closed.

It was completed per https://github.com/lightninglabs/loop/pull/673/commits/295befd083d0338f17d1ba11c92f040a49799138#diff-005fcade827e716a352a3d1d3c65f153687096adee7029e3d2924f037dd7efd4

**Comment by levmi** [comment]
Thanks!
