### ISSUE TITLE
loop terms fails with connection refused error

### ISSUE THREAD

**Issue by ShahanaFarooqui** [lightninglabs/loop#646]
loopd successfully responds to some methods like getinfo, listswaps etc but fails with others like terms, quote etc.

**To reproduce**
Run `loopd --network=regtest --lnd.macaroonpath=<USER-HOME>/.lnd/l1-regtest/data/chain/bitcoin/regtest/admin.macaroon --lnd.tlspath=<USER-HOME>/.lnd/l1-regtest/tls.cert --server.host=127.0.0.1:11010`

Open another terminal and run:

`loop --network=regtest --loopdir=<USER-HOME>/.loop/l1-regtest terms`, it throws an error as:

```
Loop Out
--------
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11009: connect: connection refused"

Loop In
------
rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:11009: connect: connection refused"

```

`loop --network=regtest --loopdir=<USER-HOME>/.loop/l1-regtest getinfo` and it will successfully return information like below:

```
{
    "version": "0.25.2-beta commit=",
    "network": "regtest",
    "rpc_listen": "localhost:11010",
    "rest_listen": "localhost:8081",
    "macaroon_path": "<USER-HOME>/.loop/l1-regtest/regtest/loop.macaroon",
    "tls_cert_path": "<USER-HOME>/.loop/l1-regtest/regtest/tls.cert",
    "loop_out_stats": {
        "pending_count": "0",
        "success_count": "0",
        "fail_count": "0",
        "sum_pending_amt": "0",
        "sum_succeeded_amt": "0"
    },
    "loop_in_stats": {
        "pending_count": "0",
        "success_count": "0",
        "fail_count": "0",
        "sum_pending_amt": "0",
        "sum_succeeded_amt": "0"
    }
}
```

**System information**
Standalone lnd & loop on regtest
Interactng with loop cli
Tested with v0.25.2 and v0.26.3
Installed from github release page
OS: Ubuntu 22.04
My lnd and loop directory locations are NOT set to their default locations.

**Comment by hieblmi** [comment]
I can confirm the reported behavior in regtest but not in prod.

**Comment by ShahanaFarooqui** [comment]
No, still getting the same error.

**Comment by hieblmi** [comment]
@ShahanaFarooqui is the loop server running in your setup as well?
You could compare to a sample setup in regtest: https://github.com/lightninglabs/loop/blob/master/regtest/README.md#using-the-loop-server-in-an-existing-setup

**Comment by ShahanaFarooqui** [comment]
No, it wasn't :P. Sorry, missed such a logical step. Should read documentation more :D.
