### ISSUE TITLE
Loop On? Swapping between two existing channels

### ISSUE THREAD

**Issue by gijswijs** [lightninglabs/loop#66]
I can imagine use cases where it would be convenient to use balance from one channel to refill a depleted channel. It would be an off-chain to off-chain swap, hence the proposed name *Loop On*.

Is this a use case that is on the roadmap?

**Comment by alexbosworth** [comment]
Is this something that you need Loop for? Can you just send from one filled channel to your depleted channel? Maybe I am misunderstanding something?

Loop On
Alex Bosworth

**Comment by gijswijs** [comment]
Yes, you can just send from on filled channel to your depleted channel, but that doesn't increase the capacity of the channel. If you want to increase the capacity of the channel you have to use Loop In. Currently you can re-balance your channels, but you can't re-balance channel capacity with lightning payments.
That's where Loop On would come in, in my view.

A second use case would be to use it for balance obfuscation. Currently it's simple to probe nodes with what's been coined Channel Balance Discovery. I think Loop On could help making these attacks less feasible.
Disclaimer: I'm researching these type of attacks.

Loop On, brother.
Gijs van Dam

**Comment by alexbosworth** [comment]
Loop doesn't alter the capacity of your channels, so I'm still confused about what the difference is? What does capacity mean to you?

**Comment by halseth** [comment]
I think _splicing_ is what you're after.

**Comment by gijswijs** [comment]
I'm sorry, I took a deeper dive in to Loop and I now understand I made a wrong assumption. Capacity does stay the same. Thanks for the feedback! Will close this issue now.
