### ISSUE TITLE
OutOfRange: amount above current maximum

### ISSUE THREAD

**Issue by grunch** [lightninglabs/loop#67]
Hi, I just got the last loop version and I found out that I can't loop out, I'm working on `testnet`
```
$ loop out 250000
Max swap fees for 250000 Loop Out: 6799
CONTINUE SWAP? (y/n), expand fee detail (x): x

Max on-chain fee:                 411
Max off-chain swap routing fee:   5010
Max off-chain prepay routing fee: 36
Max swap fee:                     1342
Max no show penalty:              1337
CONTINUE SWAP? (y/n): y
[loop] rpc error: code = Unknown desc = cannot initiate swap: rpc error: code = OutOfRange desc = amount above current maximum
```
I have enough liquidity, it is very weird to get that message cause the min and max are 250000 and 2000000

commit: e8d696e11924b2a5a04802100d9148b61f3cbb8f
lnd: version 0.6.1-beta commit=v0.6.1-beta-266-gc8ef9a4f63b235dd389a8edb09c955ea060ad971
Bitcoin Core RPC client version v0.17.1

**Comment by alexbosworth** [comment]
This is an operational issue, the testnet service has had too many swaps and is out of on-chain funds atm, will address

**Comment by alexbosworth** [comment]
I'd try again in 15 min?

**Comment by grunch** [comment]
now is working, thanks, but I still think the message is wrong, I think that's something to change in the server and not in the client, closing this issue
