### ISSUE TITLE
Mistakenly sent 300.000 sats for a 250.000 loop in

### ISSUE THREAD

**Issue by abcb1122** [lightninglabs/loop#726]
Sent 300.000 sats for a 250.000 loop in. Funds remain in the HTLC address, used version v0.28.0-beta.
Used the chantools recoverloopin to get the sweep transaction but when using the bitcoin-cli sendrawtransaction I get the following message:
error code: -26
error message:
mandatory-script-verify-flag-failed (Invalid Schnorr signature)

**Comment by abcb1122** [comment]
HTLC address was funded from an external wallet.

**Comment by hieblmi** [comment]
Hi @abcb1122, thanks for raising this. 
The `chantools` recovery should work once the expiry on your loop-in deposit has been reached, which I believe is 1000 blocks.

However, since loop v0.28.0-beta, the wrongly deposited amount should get swept back to your wallet once it is timed out.

**Comment by hieblmi** [comment]
Saw your message on Slack.

Are you able to provide your loop client logs on the github issue you raised? And also the chantools command that's causing the error above?

**Comment by abcb1122** [comment]
Hello, 

:~ $ chantools recoverloopin \
>     --txid cd12...2e73 \
>     --vout 0 \
>     --swap_hash e50c...5033 \
>     --loop_db_dir /mnt/.../mainnet \
>     --sweepaddr fromseed \
>     --feerate 20

:~ $ bitcoin-cli sendrawtransaction 0200...0c00

**Comment by hieblmi** [comment]
And do you still have loop client logs from the time the htlc was timing out? We should see in the logs why it wasn't swept back automatically.

**Comment by abcb1122** [comment]
Hello, yes I have the logs, is ok to share here? No sensitive data?

**Comment by hieblmi** [comment]
If you feel more comfortable with sending them to me you can do it to hieblmi (a)(t) lightning.engineering

**Comment by abcb1122** [comment]
ok mr, sent.
Thanks

**Comment by abcb1122** [comment]
Solved, thank you very much!
