### ISSUE TITLE
loop out failed (off-chain failure) - funds seemed like never returned back into channels - but they did after 100 blocks

### ISSUE THREAD

**Issue by merclyn** [lightninglabs/loop#744]
Title says it all, not sure how to proceed. This seems like technical issue, but also would greatly appreciate assistance with getting funds back into channels.

**Comment by merclyn** [comment]
I see there are active HTLC's. maybe there is still hope of funds coming back.

**Comment by bhandras** [comment]
Could you please give us some more details? What is the swap hash of the affected loop out?

**Comment by merclyn** [comment]
BTW, it failed because while they were in status "Initiated" I was working on another issue, and regenerated the TLS certs, and im sure that was a mistake now.

**Comment by merclyn** [comment]
is the swap hash the ID?

**Comment by merclyn** [comment]
the loop  id is: Yc5zjXZlOwdHINF8iVeIzIAuybkFalvloO+eyG747vY=

**Comment by bhandras** [comment]
If you're using the cli, you can run ```loop listswaps``` and send us the output for the affected swap.

**Comment by merclyn** [comment]
{
    "swaps": [
        {
            "amt": "24160000",
            "id": "61ce738d76653b074720d17c895788cc802ec9b9056a5be5a0ef9ec86ef8eef6",
            "id_bytes": "61ce738d76653b074720d17c895788cc802ec9b9056a5be5a0ef9ec86ef8eef6",
            "type": "LOOP_OUT",
            "state": "FAILED",
            "failure_reason": "FAILURE_REASON_OFFCHAIN",
            "initiation_time": "1715764509102460634",
            "last_update_time": "1715781583591880451",
            "htlc_address": "bc1phf3439wealjzclsqxl7rej64necnlxt8d8tndk4lu6dfpmwm8jfq72hk8w",
            "htlc_address_p2wsh": "",
            "htlc_address_p2tr": "bc1phf3439wealjzclsqxl7rej64necnlxt8d8tndk4lu6dfpmwm8jfq72hk8w",
            "cost_server": "0",
            "cost_onchain": "0",
            "cost_offchain": "0",
            "last_hop": "",
            "outgoing_chan_set": [],
            "label": ""
        }
    ]
}

**Comment by bhandras** [comment]
Your swap HTLC was confirmed here https://mempool.space/address/bc1phf3439wealjzclsqxl7rej64necnlxt8d8tndk4lu6dfpmwm8jfq72hk8w. The swap will timeout in 100 blocks, and once the HTLC is swept back, the swap invoice will be canceled and your funds should return.

**Comment by merclyn** [comment]
ok, sounds good.  its great to see how there are builtin safeguards built in to deal with these things.

**Comment by merclyn** [comment]
after 100 blocks I noticed that the HTLC expires after another 500 blocks so looks like im waiting abit more.  all good but leave this open just incase.

**Comment by merclyn** [comment]
the funds came back into channel.  good design. I need to study up some more about how the swaps/HTLC work.
if possible can we delete this entire issue?

**Comment by bhandras** [comment]
Awesome! Closing this.
