### ISSUE TITLE
Automate Instant Inbound Liquidity With Invoices

### ISSUE THREAD

**Issue by ecurrencyhodler** [lightninglabs/loop#76]
I'd like to propose a way for instant inbound liquidity to be automated via invoices.  It's similar to Thor's instant channel but this proposal would only be valuable if it becomes a standard across all lightning implementations and wallets.  It won't work if it's limited to just one Lightning wallet.  However, Loop might be a great place to start and test this feature, especially because it is geared towards reducing the friction LN end users face.  This proposal can also help make Loop In's more practical by automating inbound liquidity instantly.

**Proposal:** Automate Instant Inbound Liquidity With Invoices

**Problem:** Waiting for inbound liquidity as channel establishes when you first come online and want to receive a LN payment.

**Solution:** Embedding the node uri of the invoice creator, along with amount to be routed.

**Scenario:** 
1. Bob wants to send me 100,000 sats.
2. My node just came online and has 0 inbound liquidity.
3. I create an invoice for 100,000 sats.  My LN node recognizes I have 0 inbound liquidity so my wallet also embeds my URI in the invoice.
4. Bob’s wallet sees an invoice + uri.  Maybe even tries to route.  When it doesn’t see anything, it auto opens a channel + pushes 100,000 sat payment.
5. I now own and can spend 100,000 sats instantly.

**Considerations:**
- This auto establishing of channels and pushing payments isn’t for all LN nodes.  Just routing nodes.
- Bob doesn’t need to be the one to establish the channel.  He can push the information down the line until a node dedicated to routing is found.  The routing node can then be the one to establish the channel with me.
- Certain specifics need to be flushed out such as the size of Bob’s channel.  Right now I think Bob can manually set the size of the channels to be established on his end.  Should be smaller channels at first.  If the person gets paid again, just establish another channel towards the same node if there isn't enough capacity.
- Routing nodes who provide this service can charge a premium.
- Bob, as a liquidity provider, won't cheat against himself so I can make LN payments instantly.
- The beauty behind this proposal is that I can receive a payment instantly, I can send payments instantly, and that it hides everything from me as an end user.
- Can possibly be extended to neutrino LN wallets if they are public.

**Comment by joostjager** [comment]
Thanks for taking the time to write down this proposal. However, at the moment everything that involves establishing a new channel is outside the scope of the loop project. Closing the issue to keep the issue database focused.
