### ISSUE TITLE
"Unable to obtain macaroons" when starting loopd

### ISSUE THREAD

**Issue by bucko13** [lightninglabs/loop#78]
I'm wondering if maybe the README is out of date or incomplete, but when I follow the instructions there and clear the existing macaroons for a running instance of lnd cloned from master, I get an error about missing macaroons. When I run `lncli unlock` to unlock the wallet then the macaroons are generated and then `loopd` starts up ok even though it breaks the expectation in the README that there should be no macaroons when first starting up `loopd`. Is `loopd` only expected to work with unencrypted wallets then?

**Comment by alexbosworth** [comment]
Maybe it's confusingly worded, the no-macaroons refers to a dance related to rebuilding lnd from a build that didn't have the correct build tags but then having legacy macaroons from the previous build

**Comment by bucko13** [comment]
Ah! Gotcha. Ok, that makes more sense. So unlocking the wallet first is expected behavior. Thanks!
