### ISSUE TITLE
Missing last_hop data in ListSwaps

### ISSUE THREAD

**Issue by rsafier** [lightninglabs/loop#798]
docs for loop say `last_hop` should be populated if it was spent in the original request, which is all the loop ins we have done, but `ListSwaps` doesn't seem to have any populated in the return object.

**Expected behavior**
if I have a Loop In that has completed successfully with the `last_hop` being `035e4ff418fc8b5554c5d9eea66396c227bd429a3251c8cbc711002ba215bfc226` (WalletOfSatoshi) we expect from the documentation that it will be returned in the `ListSwap` response object.

**Actual behavior**
All `last_hop` values returned from `ListSwap` appear to be empty.

**To reproduce**
- make Loop In to a specific `last_hop`
- run ListSwap and it doesn't return the used value for `last_hop` to gRPC consumer.

**System information**

Deployed standalone docker to remote node.

Interface: CLI and gRPC

Version: 0.26.8

Ubuntu 22.04 LTS

**Comment by starius** [comment]
Thanks for the report! The team is looking into the issue.

**Comment by starius** [comment]
The fix was merged into `master` in https://github.com/lightninglabs/loop/pull/806

**Comment by starius** [comment]
The fix is included in release [v0.28.7-beta](https://github.com/lightninglabs/loop/releases/tag/v0.28.7-beta).
