### ISSUE TITLE
cost_offchain is always 0

### ISSUE THREAD

**Issue by rsafier** [lightninglabs/loop#799]
**Expected behavior**

'cost_offchain' reflects final offchain costs of the loop transaction.

**Actual behavior**
'cost_offchain' is always 0.

**To reproduce**
- do some loop ins
- call `ListSwaps` and 'cost_offchain' = 0 on all returned records.

**System information**

V0.28.6 loopd standalone, CLI

Ubuntu 22.04 LTS

**Comment by ffranr** [comment]
Thanks for the report, I'll let the team know.

**Comment by bhandras** [comment]
Note that for loopin there's no offchain cost on the user side, as the routing fee is paid by the server and is included in the swap fee.
