### ISSUE TITLE
Loop out quote RPC has undocumented required `conf` parameter

### ISSUE THREAD

**Issue by wbobeirne** [lightninglabs/loop#81]
Calling `/v1/loop/out/quote/{amt}` as is gets you the following error:

> API error calling GET /v1/loop/out/quote/1000000 UnknownServerError: a confirmation target of at least 2 must be provided

The [docs show no mention of a confirmation target parameter](https://lightning.engineering/loop/rest/index.html#v1-loop-out-quote), but adding the param `?conf_target=2` (or higher) fixes the issue. This argument should be documented, and should probably have a reasonable default.

**Comment by wpaulino** [comment]
The parameter is now documented. The reason it is required is to force users to think about a sensible value as it impacts the cost of the swap.
