### ISSUE TITLE
loop in external doesn't work if there's no onchain funds

### ISSUE THREAD

**Issue by grunch** [lightninglabs/loop#84]
I'm trying to do a `loop in --amt 250000 --external` and I got this response
```
[loop] rpc error: code = Unknown desc = insufficient funds available to construct transaction
```
I have more than 50 channels with plenty inbound capacity, at that moment I had 13451 satoshis on-chain wallet balance, so I sent to my node 1000000 onchain btc and after that I could run the same command, I understand that loop in always is looking for that `--amt` in the node wallet to make the swap and is ignoring the `--external` flag.

**Comment by guggero** [comment]
Can confirm it's a bug in `loopd`, the fee estimation fails because there are no UTXOs to use for the estimation transaction.
I'll come up with a fix.
