### ISSUE TITLE
Loop out - Minimise required arguments for REST API

### ISSUE THREAD

**Issue by jlucid** [lightninglabs/loop#87]
**Summary**

The REST API for [loop out](https://lightning.engineering/loop/rest/index.html#v1-loop-out) requires the user to pass argument values for **max_swap_fee** and **max_prepay_amt** in order to avoid the errors "swap fee too high" and  "prepay amount too high", respectively. However, these same arguments are not required by the loop CLI, as shown below.

$ ./loop out | tail -n 6
OPTIONS:
   --channel value      the 8-byte compact channel ID of the channel to loop out (default: 0)
   --addr value         the optional address that the looped out funds should be sent to, if let blank the funds will go to lnd's wallet
   --amt value          the amount in satoshis to loop out (default: 0)
   --conf_target value  the number of blocks from the swap initiation height that the on-chain HTLC should be swept within (default: 6)

**Task 1**

Minimise the number of required arguments for REST API so that it is more consistent with the loop CLI . 

**Task 2**
 
**sweep_conf_target** is also a required argument for the REST API so needs to be added to the documentation page linked to above. If possible, renaming to "conf_target" would also be nice to match loop CLI

Thanks 

**Errors seen:**

```bash
q)input
amt              | "250000"
dest             | "bc1qtumg8sp356nwekne62muprjcj5pj8rkn37c43y"
sweep_conf_target| 2
max_swap_fee     | "2000"
q).loopd.loopOut[input]
error  | "prepay amount too high"
message| "prepay amount too high"
code   | 2

q)input
amt              | "250000"
dest             | "bc1qtumg8sp356nwekne62muprjcj5pj8rkn37c43y"
sweep_conf_target| 2
max_prepay_amt   | "50000"
q).loopd.loopOut[input]
error  | "swap fee too high"
message| "swap fee too high"
code   | 2

```

`

**Comment by guggero** [comment]
The CLI also sends these values to `loopd` through the gRPC interface.
They are obtained by first calling the `LoopOutQuote` method and then using the returned values for the `LoopOut` method.
Maybe the documentation for `LoopOut` should just mention that a quote should be fetched from `loopd` first to get values for these parameters?

**Comment by jlucid** [comment]
Oh I see, so the CLI does the work under the cover. Actually the documentation does mention where good values can be obtained, so I think just tagging those args as required for the REST API would help, leaving max_prepay_routing_fee and max_miner_fee as marked optional.

**Comment by jlucid** [comment]
I think this one can be closed. I dont think the number of args can be minimised for the REST API as a good value needs to be passed in for all of them in my experience to get a successful swap.  Also, I shouldn't be comparing how REST works with how the CLI works, the CLI tries to minimise effort for the user by doing the same thing under the covers.

Task 2 is just to be consistent in naming of input params so low priority stuff
@guggero

**Comment by guggero** [comment]
You are right, it looks like the documentation is out of date. We'll update it and then close the ticket, thanks!

**Comment by guggero** [comment]
The documentation has been updated in the meantime.
