### ISSUE TITLE
Feature request - Loop in to a specific channel

### ISSUE THREAD

**Issue by MrManPew** [lightninglabs/loop#96]
Hi, I think it is not possible yet to loop-in to a specific channel, can this be a feature request for adding a option to loop in to a specific channel?

Thanks

**Comment by MrManPew** [comment]
https://github.com/lightningnetwork/lnd/pull/3739#issuecomment-555087235

**Comment by carlaKC** [comment]
Loop in allows you to specify a `--last_hop` which will get you pretty close to the channel you want? Unless you have a lot of channels open with one peer.

**Comment by joostjager** [comment]
The last hop restriction has been merged into `loop`. Closing this issue. Let us know if you have a use case for more fine-grained channel selection.
