### ISSUE TITLE
Swap server doesn't pay the "loop in" invoice if the route is "too expensive"

### ISSUE THREAD

**Issue by selevit** [lightninglabs/loop#97]
I am trying to make "loop in" in mainnet. Firstly I requested the "loop in" for 250k sat.

```bash
2019-10-15T14:35:30Z LOOP_IN HTLC_PUBLISHED 0.0025 BTC - 3Ewy6ussedPqFNu2ZDhqMs1te43XR1wBpC
```

And I also set up the inbound channel for 500k sat with bitrefill.

```json
{
      "active": true,
      "remote_pubkey": "030c3f19d742ca294a55c00376b3b355c3c90d61c6b6b39554dbc7ac19b141c14f",
      "channel_point": "bc273428dbba483a4c9bafe283348f4c53f15e0ff925058a92e97ac47a6ac6bf:0",
      "chan_id": "659188007361380352",
      "capacity": "500000",
      "local_balance": "0",
      "remote_balance": "497114",
      "commit_fee": "2886",
      "commit_weight": "552",
      "fee_per_kw": "3987",
      "unsettled_balance": "0",
      "total_satoshis_sent": "0",
      "total_satoshis_received": "0",
      "num_updates": "23",
      "pending_htlcs": [],
      "csv_delay": 144,
      "private": false,
      "initiator": false,
      "chan_status_flags": "ChanStatusDefault",
      "local_chan_reserve_sat": "5000",
      "remote_chan_reserve_sat": "5000"
}
```

The funds were deposited to the `3Ewy6ussedPqFNu2ZDhqMs1te43XR1wBpC` address, but the "swap" invoice is not paid yet:

```
lnbc2489750n1pw6tkfjpp58muxgn7svw4afh9jts8vej8nfr9mnt4zmkcxa2zz49gwe8l4vqpsdq8wdmkzuqcqzpgxq97zvuqvfdheqar07vrpa79kv6eq4mzhgamsej9eztt0mccfzrpa9jdl4f4ssr3w294chq8qt7z40rp8u8gemzqvhdtgq6v0clqvte5wgvxh5sppyvgc0
```

I checked this invoice on submarineswaps.org by the suggestion given from @alexbosworth .
Firstly I got an error `No route found to execute this swap. Try a smaller amount?`. 
Then, as far as I understood, @alexbosworth changed the "max fee" option on submarineswaps.org and it fixed the error.

But anyway, the swap server cannot pay my "swap" invoice because the route seems too expensive.
I think this condition should be validated at the beginning of "loop in" operation.
Or it will be even better to support various fee rates for inbound channels.

**Comment by Roasbeef** [comment]
This service and `submarineswaps.org` are independent. Agree that we can attempt to validate things up front to avoid issues like this. We're working on integrating a pre-acceptance check for reachability, cc @joostjager.
